<?php
namespace console\components\traits;

use Yii;

/**
 * Trait MainControllerTrait
 * @package console\components\traits
 */
trait MainControllerTrait {

    public $frontendPath;

    /** @inheritdoc */
    public function init()
    {
        $commonPath = Yii::getAlias('@common/config');
        $consolePath = Yii::getAlias('@console/config');

        $frontendPath = $this->frontendPath;

        $params = array_merge(
            require($commonPath . '/params.php'),
            file_exists($commonPath . '/params-local.php') ? (array)(require($commonPath . '/params-local.php')) : [],
            require($consolePath . '/params.php'),
            file_exists($consolePath . '/params-local.php') ? (array)(require($consolePath . '/params-local.php')) : [],
            require($frontendPath . '/params.php'),
            file_exists($frontendPath . '/params-local.php') ? (array)(require($frontendPath . '/params-local.php')) : []
        );

        Yii::$app->params = $params;

        $db = array_merge(
            require($frontendPath. '/db.php'),
            file_exists($frontendPath . '/db-local.php') ? (array)(require($frontendPath . '/db-local.php')) : []
        );

        foreach ($db as $name => $options) {
            Yii::$app->set($name, $options);
        }

        if (file_exists($frontendPath . '/bootstrap.php')) {
            require($frontendPath . '/bootstrap.php');
        }

        parent::init(); // TODO: Change the autogenerated stub
    }
}