<?php
namespace admin\components;

use common\models\gateways\Admins;
use Yii;
use yii\web\User;

/**
 * Class CustomUser
 * @package admin\components
 */
class CustomUser extends User
{
    /**
     * @param Admins $identity
     * @param bool $cookieBased
     * @param int $duration
     * @return bool
     */
    protected function beforeLogin($identity, $cookieBased, $duration)
    {
        return parent::beforeLogin($identity, $cookieBased, $duration); // TODO: Change the autogenerated stub
    }

    /**
     * @param Admins $identity
     * @param bool $cookieBased
     * @param int $duration
     */
    protected function afterLogin($identity, $cookieBased, $duration)
    {
        parent::afterLogin($identity, $cookieBased, $duration); // TODO: Change the autogenerated stub
    }

    /**
     * @param Admins $identity
     */
    protected function afterLogout($identity)
    {
        parent::afterLogout($identity); // TODO: Change the autogenerated stub
    }
}