<?php
namespace my\components;

use Yii;

/**
 * MainController controller
 */
class MainController extends \common\components\MainController
{
    public function beforeAction($action)
    {
        if (0 === strpos(Yii::$app->request->url, '/' . Yii::$app->params['superadminUrl'] . '/')) {
            if (Yii::$app->superadmin->isGuest) {
                $this->layout = '@my/modules/superadmin/views/layouts/guest.php';
            } else {
                $this->layout = '@my/modules/superadmin/views/layouts/superadmin.php';
            }
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}