INSERT INTO `notification_email` (`id`, `subject`, `message`, `code`, `enabled`) VALUES
(1,	'Panel created',	'Panel created',	'panel_created',	1),
(2,	'Restore password',	'Restore password',	'restore_password',	1),
(3,	'Email changed',	'Email changed',	'email_changed',	1),
(4,	'Password changed',	'Password changed',	'password_changed',	1),
(5,	'Panel has beed frozen',	'Panel has beed frozen',	'panel_frozen',	1),
(6,	'Panel will be expired',	'Panel will be expired',	'panel_expired',	1),
(7,	'2Checkout payment under review',	'2Checkout payment under review',	'2checkout_review',	1),
(8,	'2Checkout fraud review passed',	'2Checkout fraud review passed',	'2checkout_pass',	1),
(9,	'2Checkout fraud review failed',	'2Checkout fraud review failed',	'2checkout_failed',	1),
(10,	'Domain created',	'Domain created',	'domain_issued',	1),
(11,	'SSL certificate issued',	'SSL certificate issued',	'ssl_issued',	1),
(12,	'Invoice created',	'Invoice created',	'invoice_created',	1),
(13,	'New message',	'New message',	'new_message',	1),
(14,	'New ticket',	'New ticket',	'new_ticket',	1);