<?php

return [
    '1001' => 'Create user',
    '1002' => 'Update user',
    '1003' => 'Generate user API key',
    '1004' => 'Activate user',
    '1005' => 'Deactivate user',
    '1006' => 'Update password',
    '1007' => 'Update custom rates',
    '1008' => 'Copy custom rates',
    '1009' => 'Reset custom rates',
    '1010' => 'Superadmin sign in as user',
    '1011' => 'Export users',
    '1012' => 'Download export users',

    '2001' => 'Add service',
    '2002' => 'Edit service',
    '2003' => 'Add subscription',
    '2004' => 'Edit description',
    '2005' => 'Delete service',
    '2006' => 'Enable service',
    '2007' => 'Disable service',
    '2008' => 'Reset custom rates',
    '2009' => 'Edit description',
    '2010' => 'Add category',
    '2011' => 'Edit category',
    '2012' => 'Delete category',
    '2013' => 'Enable category',
    '2014' => 'Disable category',
    '2016' => 'Move Service',
    '2017' => 'Move Category',
    '2018' => 'Assign Category',

    '3001' => 'Add provider',
    '3002' => 'Edit provider',
    '3003' => 'Delete provider',
    '3004' => 'View provider list',

    '3101' => 'Add bonus',
    '3102' => 'Edit bonus',

    '3201' => 'Panel name changed',
    '3202' => 'Timezone changed',
    '3203' => 'Currency format changed',
    '3204' => 'Ticket system changed',
    '3205' => 'Max pending tickets changed',
    '3206' => 'Registration page changed',
    '3207' => 'Terms checkbox changed',
    '3208' => 'Skype field changed',
    '3209' => 'Name fields changed',
    '3210' => 'Forgot password changed',
    '3211' => 'Custom header changed',
    '3212' => 'Custom footer changed',
    '3213' => 'Logo upload',
    '3214' => 'Logo delete',
    '3215' => 'Favicon upload',
    '3216' => 'Favicon delete',

    '3301' => 'Add payment method',
    '3302' => 'Edit payment method',
    '3303' => 'Activate payment method',
    '3305' => 'Deactivate payment method',
    '3304' => 'Sort payment method',

    '5001' => 'Approve payout',
    '5002' => 'Reject payout',
    '5003' => 'Commission rate updated',
    '5004' => 'Minimum payout updated',
    '5005' => 'Approve payouts status updated',

    '8' => 'Resend order',
    '9' => 'Change status',
    '10' => 'Cancel and refund',
    '11' => 'Set start count',
    '12' => 'Set partial',
    '13' => 'Add payment',
    '14' => 'Change status',
    '15' => 'Submit message',
    '16' => 'Authorization',
    '21' => 'Up service',                       // Only for old events support, without new records
    '22' => 'Down service',                     // Only for old events support, without new records
    '33' => 'Service description changed',      // Only for old events support, without new records
    '36' => 'Edit method',
    '39' => 'Change password',
    '44' => 'Preferences changed',
    '45' => 'Up menu',
    '46' => 'Down menu',
    '50' => 'Change status',
    '53' => 'Edit link',
    '55' => 'Make hidden',
    '56' => 'Make visible',
    '61' => 'Close ticket',
    '62' => 'Add ticket',
    '63' => 'Export users',
    '64' => 'Name fields changed',
    '65' => 'Up language',
    '66' => 'Down language',
    '72' => 'Edit page',
    '73' => 'Edit menu',
    '76' => 'Activate theme',
    '77' => 'Reset changes',
    '78' => 'Edit code',
    '79' => 'Edit language',
    '80' => 'Add language',
    '81' => 'Reset changes',
    '82' => 'Change status',
    '83' => 'Up method',
    '84' => 'Down method',
    '86' => 'Set default',
    '87' => 'Cancel and refund',
    '88' => 'Mark as unread',
    '89' => 'Delete message',
    '90' => 'Edit message',
    '91' => 'Change expiry',
    '92' => 'Edit payment',
    '93' => 'Open unread ticket',
    '94' => 'Delete ticket',

//    '' => 'Add custom rates',
//    '' => 'Reset all custom rates',
//    '' => 'Edit message',
//    '' => 'Delete message',
//    '' => 'Mark as unread',
//    '' => 'Export orders',
];