<?php
namespace common\components;

use Yii;
use yii\helpers\Json;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\View;

/**
 * MainController controller
 */
class MainController extends Controller
{
    /**
     * Activate js module
     * @param string $name
     * @param array $options
     */
    public function addModule($name, $options = [])
    {
        $this->getView()->registerJs('window.modules.' . $name . ' = ' . Json::encode($options) . ';', View::POS_END);
    }

    public function beforeAction($action)
    {
        // Validate post requests
        if (Yii::$app->request->isPost) {
            $refererDomain = !empty($_SERVER['HTTP_REFERER']) ? parse_url($_SERVER['HTTP_REFERER'], PHP_URL_HOST) : null;
            if ($refererDomain !== $_SERVER['SERVER_NAME']) {
                throw new BadRequestHttpException(Yii::t('yii', 'Unable to verify your data submission.'));
            }
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}