<?php

use yii\db\Migration;

/**
 * Class m180406_144505_db_store_table_pages___default_page_added
 */
class m180406_144505_db_store_table_pages___default_page_added extends Migration
{
    /**
     * @var
     */
    protected $dbName;

    public function init()
    {
        $this->dbName = Yii::$app->params['storeDefaultDatabase'];
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {

    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        echo "m180406_144505_db_store_table_pages___default_page_added cannot be reverted.\n";

        return false;
    }

    public function up()
    {
        $this->execute("
            USE $this->dbName;
            INSERT INTO `pages` (`id`, `title`, `visibility`, `content`, `seo_title`, `seo_description`, `seo_keywords`, `url`, `template`, `deleted`, `created_at`, `updated_at`) VALUES ('', 'Privacy policy', '1', '', 'Privacy policy', NULL, NULL, 'privacypolicy', 'page', '0', NULL, NULL);
        ");

        $this->execute("
            USE $this->dbName;
            UPDATE `pages` SET `url` = 'termsofservice' WHERE `url` = 'terms-of-service';
            UPDATE `pages` SET `url` = 'contactus' WHERE `url` = 'contact-us';
        ");
    }

    public function down()
    {
        $this->execute("
            USE $this->dbName;
            DELETE FROM `pages` WHERE `url` = `privacypolicy`;
        ");

        $this->execute("
            USE $this->dbName;
            UPDATE `pages` SET `url` = 'terms-of-service' WHERE `url` = 'termsofservice';
            UPDATE `pages` SET `url` = 'contact-us' WHERE `url` = 'contactus';
        ");
    }
}
