<?php

use yii\db\Migration;

/**
 * Class m180705_090851_db_store_table_language_field_rtl_added
 */
class m180705_090851_db_store_table_language_field_rtl_added extends Migration
{
    /**
     * Store databases
     * @var
     */
    private $databases;

    /**
     * {@inheritdoc}
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $databases = (new \yii\db\Query())->select([
            'db_name',
        ])->from(DB_STORES . '.stores')->column();

        $databases[] = Yii::$app->params['storeDefaultDatabase'];

        foreach ($databases as $key => $db) {
            $dbExist = Yii::$app->db
                ->createCommand("SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = '$db'")
                ->queryScalar();

            if (!$dbExist) {
                unset($databases[$key]);
            }
        }

        $this->databases = $databases;
    }

    /**
     * {@inheritdoc}
     */
    public function up()
    {
        foreach ($this->databases as $db) {
            // Add rtl field
            $this->execute("
                ALTER TABLE  `{$db}`.`languages` ADD `rtl` TINYINT(1)  NOT NULL  AFTER `code`;
            ");

            // Update rtl for each store languages
            $storeLanguages = (new \yii\db\Query())
                ->select('code')
                ->from("`{$db}`.`languages`")
                ->column();

            foreach ($storeLanguages as $langCode) {
                $rtlVal = (int)\yii\helpers\ArrayHelper::getValue(Yii::$app->params['languages'], [$langCode, 'rtl'], false);

                $this->execute("
                    UPDATE  `{$db}`.`languages` SET `rtl` = $rtlVal WHERE `code` = '$langCode';
                ");
            }
        }
    }

    /**
     * {@inheritdoc}
     */
    public function down()
    {
        foreach ($this->databases as $db) {
            $this->execute("
              ALTER TABLE  `{$db}`.`languages ` DROP `rtl `;
            ");
        }
    }
}