-- MySQL Script generated by MySQL Workbench
-- Sun Oct 29 21:25:01 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema stores
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema stores
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stores` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema store
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema store
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `store` ;
USE `stores` ;

-- -----------------------------------------------------
-- Table `stores`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stores`.`customers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(64) NULL,
  `first_name` VARCHAR(255) NULL,
  `last_name` VARCHAR(255) NULL,
  `access_token` VARCHAR(64) NULL,
  `token` VARCHAR(64) NULL,
  `status` TINYINT(1) NULL COMMENT '1 - active, 2 - suspended',
  `created_at` INT NULL,
  `updated_at` INT NULL,
  `last_login` VARCHAR(255) NULL,
  `timezone` INT NULL,
  `auth_token` VARCHAR(64) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stores`.`stores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stores`.`stores` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `customer_id` INT NULL,
  `domain` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL,
  `timezone` INT NULL,
  `db_name` VARCHAR(255) NULL,
  `expired` INT NULL,
  `created_at` INT NULL,
  `updated_at` INT NULL,
  `logo` VARCHAR(255) NULL,
  `favicon` VARCHAR(255) NULL,
  `currency` VARCHAR(10) NULL,
  `seo_title` VARCHAR(255) NULL,
  `seo_keywords` VARCHAR(2000) NULL,
  `seo_description` VARCHAR(2000) NULL,
  `theme_name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_customer_id_stores_idx` (`customer_id` ASC),
  CONSTRAINT `fk_customer_id_stores`
    FOREIGN KEY (`customer_id`)
    REFERENCES `stores`.`customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stores`.`payment_methods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stores`.`payment_methods` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `store_id` INT(11) NULL DEFAULT NULL,
  `method` VARCHAR(255) NULL DEFAULT NULL,
  `details` MEDIUMTEXT NULL DEFAULT NULL,
  `active` TINYINT(1) NULL DEFAULT NULL COMMENT '0 - disabled, 1 - enabled',
  PRIMARY KEY (`id`),
  INDEX `fk_store_id_method_idx` (`store_id` ASC),
  CONSTRAINT `fk_store_id_method`
    FOREIGN KEY (`store_id`)
    REFERENCES `stores`.`stores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stores`.`providers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stores`.`providers` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `site` VARCHAR(45) NULL DEFAULT NULL,
  `type` TINYINT(1) NULL DEFAULT NULL COMMENT '0 - internal, 1 - external',
  `created_at` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stores`.`store_admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stores`.`store_admins` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `store_id` INT(11) NULL DEFAULT NULL,
  `username` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(64) NULL DEFAULT NULL,
  `auth_hash` VARCHAR(64) NULL DEFAULT NULL,
  `first_name` VARCHAR(255) NULL DEFAULT NULL,
  `last_name` VARCHAR(255) NULL DEFAULT NULL,
  `status` TINYINT(1) NULL DEFAULT NULL COMMENT '1 - active\n2 - suspended',
  `ip` VARCHAR(255) NULL DEFAULT NULL,
  `last_login` INT(11) NULL DEFAULT NULL,
  `rules` VARCHAR(1000) NULL DEFAULT NULL,
  `created_at` INT(11) NULL DEFAULT NULL,
  `updated_at` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_admin_store_id_idx` (`store_id` ASC),
  CONSTRAINT `fk_admin_store_id`
    FOREIGN KEY (`store_id`)
    REFERENCES `stores`.`stores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stores`.`store_domains`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stores`.`store_domains` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `store_id` INT(11) NULL DEFAULT NULL,
  `domain` VARCHAR(255) NULL DEFAULT NULL,
  `type` TINYINT(1) NULL DEFAULT '0' COMMENT '0 - standart, 1 - additional, 2 - subdomain',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `domain_UNIQUE` (`domain` ASC),
  INDEX `fk_domain_store_id_idx` (`store_id` ASC),
  CONSTRAINT `fk_domain_store_id`
    FOREIGN KEY (`store_id`)
    REFERENCES `stores`.`stores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stores`.`store_providers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stores`.`store_providers` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `provider_id` INT NULL,
  `store_id` INT(11) NULL DEFAULT NULL,
  `apikey` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_provider_store_id_idx` (`store_id` ASC),
  INDEX `fk_provider_provider_id_idx` (`provider_id` ASC),
  CONSTRAINT `fk_provider_store_id`
    FOREIGN KEY (`store_id`)
    REFERENCES `stores`.`stores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_provider_provider_id`
    FOREIGN KEY (`provider_id`)
    REFERENCES `stores`.`providers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stores`.`store_files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stores`.`store_files` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `store_id` INT NULL,
  `type` TINYINT(1) NULL COMMENT '1 - logo, 2 - favicon',
  `date` TEXT(65535) NULL,
  `created_at` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_files_store_id_idx` (`store_id` ASC),
  CONSTRAINT `fk_files_store_id`
    FOREIGN KEY (`store_id`)
    REFERENCES `stores`.`stores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `store` ;

-- -----------------------------------------------------
-- Table `store`.`checkouts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store`.`checkouts` (
  `id` INT(11) NOT NULL,
  `customer` VARCHAR(255) NULL DEFAULT NULL,
  `price` DECIMAL(20,2) NULL DEFAULT NULL,
  `status` TINYINT(1) NULL DEFAULT NULL COMMENT '0 - pending\n1 - paid\n',
  `method_status` VARCHAR(255) NULL DEFAULT NULL,
  `method_id` INT(11) NULL DEFAULT NULL,
  `ip` VARCHAR(255) NULL DEFAULT NULL,
  `details` MEDIUMTEXT CHARACTER SET 'utf8mb4' NULL DEFAULT NULL COMMENT 'json\nlink\nquantity\npackage_id',
  `created_at` INT(11) NULL DEFAULT NULL,
  `updated_at` INT(11) NULL DEFAULT NULL,
  `currency` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `store`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store`.`orders` (
  `id` INT(11) NOT NULL,
  `checkout_id` INT(11) NULL DEFAULT NULL,
  `customer` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_checkout_id` (`checkout_id` ASC),
  CONSTRAINT `fk_orders_checkout_id`
    FOREIGN KEY (`checkout_id`)
    REFERENCES `store`.`checkouts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `store`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store`.`products` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `position` INT(11) NULL DEFAULT '0',
  `url` VARCHAR(255) NULL DEFAULT NULL,
  `properties` VARCHAR(1000) NULL,
  `description` MEDIUMTEXT CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `visibility` TINYINT(1) NULL DEFAULT NULL,
  `seo_title` VARCHAR(45) NULL,
  `seo_description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `store`.`packages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store`.`packages` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `price` DECIMAL(10,2) NULL DEFAULT NULL,
  `quantity` INT(11) NULL DEFAULT '0',
  `link_type` TINYINT(1) NULL DEFAULT '0',
  `product_id` INT(11) NULL DEFAULT '0',
  `visibility` TINYINT(1) NULL DEFAULT '0',
  `best` TINYINT(1) NULL,
  `mode` TINYINT(1) NULL DEFAULT '0',
  `provider_id` INT(11) NULL DEFAULT '0',
  `provider_service` VARCHAR(255) NULL DEFAULT NULL,
  `position` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_packages_product_id` (`product_id` ASC),
  CONSTRAINT `fk_packages_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `store`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `store`.`suborders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store`.`suborders` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `order_id` INT(11) NULL DEFAULT NULL,
  `checkout_id` INT(11) NULL DEFAULT NULL,
  `link` VARCHAR(1000) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `amount` DECIMAL(20,5) NULL DEFAULT NULL,
  `package_id` INT(11) NULL DEFAULT NULL,
  `quantity` INT(11) NULL DEFAULT '0',
  `status` TINYINT(1) NULL DEFAULT '0' COMMENT '1 - Awaiting\n2 - Pending\n3 - In progress\n4 - Completed\n5 - Canceled\n6 - Failed\n7 - Error',
  `updated_at` INT(11) NULL DEFAULT '0',
  `mode` TINYINT(1) NULL DEFAULT '0' COMMENT '0 - manual, 1 - auto',
  `provider_id` INT(11) NULL DEFAULT NULL,
  `provider_service` VARCHAR(300) NULL DEFAULT NULL,
  `provider_order_id` VARCHAR(300) NULL DEFAULT NULL,
  `provider_charge` DECIMAL(20,5) NULL DEFAULT NULL,
  `provider_response` MEDIUMTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_item_checkout_id` (`checkout_id` ASC),
  INDEX `fk_order_item_order_id` (`order_id` ASC),
  INDEX `fk_order_item_package_id` (`package_id` ASC),
  CONSTRAINT `fk_order_item_checkout_id`
    FOREIGN KEY (`checkout_id`)
    REFERENCES `store`.`checkouts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_item_order_id`
    FOREIGN KEY (`order_id`)
    REFERENCES `store`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_item_package_id`
    FOREIGN KEY (`package_id`)
    REFERENCES `store`.`packages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `store`.`payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store`.`payments` (
  `id` INT(11) NOT NULL,
  `checkout_id` INT(11) NULL DEFAULT NULL,
  `method_id` INT(11) NULL DEFAULT NULL,
  `customer` VARCHAR(255) NULL DEFAULT NULL,
  `amount` DECIMAL(20,5) NULL DEFAULT NULL,
  `status` TINYINT(1) NULL DEFAULT '0' COMMENT '1 - Completed\n2 - Awating\n3 - Failed\n4 - Refunded',
  `fee` DECIMAL(20,5) NULL DEFAULT '0.00000',
  `transaction_id` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `country` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` INT(11) NULL DEFAULT NULL,
  `updated_at` INT(11) NULL DEFAULT '0',
  `currency` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_payments_checkout_id` (`checkout_id` ASC),
  CONSTRAINT `fk_checkout_id`
    FOREIGN KEY (`checkout_id`)
    REFERENCES `store`.`checkouts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `store`.`payments_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store`.`payments_log` (
  `id` INT(11) NOT NULL,
  `checkout_id` INT(11) NULL DEFAULT NULL,
  `result` MEDIUMTEXT NULL DEFAULT NULL,
  `ip` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_paymens_log_checkout_id` (`checkout_id` ASC),
  CONSTRAINT `id`
    FOREIGN KEY (`checkout_id`)
    REFERENCES `store`.`checkouts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `store`.`carts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store`.`carts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(64) NULL,
  `package_id` INT NULL,
  `link` VARCHAR(255) NULL,
  `created_at` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `store`.`pages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store`.`pages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `visibility` TINYINT(1) NULL,
  `content` TEXT(65535) NULL,
  `seo_title` VARCHAR(255) NULL,
  `seo_description` VARCHAR(2000) NULL,
  `url` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;