<?php

return array(
    '-1200' => 'UTC -12:00) Baker/Howland Island',
    '-1100' => 'UTC -11:00) Niue',
    '-1000' => 'UTC -10:00) Hawaii-Aleutian Standard Time, Cook Islands, Tahiti',
    '-930' => 'UTC -9:30) Marquesas Islands',
    '-900' => 'UTC -9:00) Alaska Standard Time, Gambier Islands',
    '-800' => 'UTC -8:00) Pacific Standard Time, Clipperton Island',
    '-700' => 'UTC -7:00) Mountain Standard Time',
    '-600' => 'UTC -6:00) Central Standard Time',
    '-500' => 'UTC -5:00) Eastern Standard Time, Western Caribbean Standard Time',
    '-430' => 'UTC -4:30) Venezuelan Standard Time',
    '-400' => 'UTC -4:00) Atlantic Standard Time, Eastern Caribbean Standard Time',
    '-330' => 'UTC -3:30) Newfoundland Standard Time',
    '-300' => 'UTC -3:00) Argentina, Brazil, French Guiana, Uruguay',
    '-200' => 'UTC -2:00) South Georgia/South Sandwich Islands',
    '-100' => 'UTC -1:00) Azores, Cape Verde Islands',
    '0' => '(UTC) Greenwich Mean Time, Western European Time',
    '100' => 'UTC +1:00) Central European Time, West Africa Time',
    '200' => 'UTC +2:00) Central Africa Time, Eastern European Time, Kaliningrad Time',
    '300' => 'UTC +3:00) Moscow Time, East Africa Time, Arabia Standard Time',
    '330' => 'UTC +3:30) Iran Standard Time',
    '400' => 'UTC +4:00) Azerbaijan Standard Time, Samara Time',
    '430' => 'UTC +4:30) Afghanistan',
    '500' => 'UTC +5:00) Pakistan Standard Time, Yekaterinburg Time',
    '530' => 'UTC +5:30) Indian Standard Time, Sri Lanka Time',
    '545' => 'UTC +5:45) Nepal Time',
    '600' => 'UTC +6:00) Bangladesh Standard Time, Bhutan Time, Omsk Time',
    '630' => 'UTC +6:30) Cocos Islands, Myanmar',
    '700' => 'UTC +7:00) Krasnoyarsk Time, Cambodia, Laos, Thailand, Vietnam',
    '800' => 'UTC +8:00) Australian Western Standard Time, Beijing Time, Irkutsk Time',
    '845' => 'UTC +8:45) Australian Central Western Standard Time',
    '900' => 'UTC +9:00) Japan Standard Time, Korea Standard Time, Yakutsk Time',
    '930' => 'UTC +9:30) Australian Central Standard Time',
    '1000' => 'UTC +10:00) Australian Eastern Standard Time, Vladivostok Time',
    '1030' => 'UTC +10:30) Lord Howe Island',
    '1100' => 'UTC +11:00) Srednekolymsk Time, Solomon Islands, Vanuatu',
    '1130' => 'UTC +11:30) Norfolk Island',
    '1200' => 'UTC +12:00) Fiji, Gilbert Islands, Kamchatka Time, New Zealand Standard Time',
    '1245' => 'UTC +12:45) Chatham Islands Standard Time',
    '1300' => 'UTC +13:00) Samoa Time Zone, Phoenix Islands Time, Tonga',
    '1400' => 'UTC +14:00) Line Island',
);
