<?php
namespace sommerce\modules\admin\components;

use common\models\stores\StoreAdminAuth;
use common\models\stores\StoreAdminsHash;
use Yii;
use yii\web\User;

/**
 * Class CustomUser
 * @package sommerce\modules\admin\components
 */
class CustomUser extends User
{
    /** @inheritdoc */
    protected function beforeLogin($identity, $cookieBased, $duration)
    {
        // Update identity data on login by login form
        /** @var StoreAdminAuth $identity */
        if ($identity && !$cookieBased) {

            $identity->deleteAuthKey();

            $identity->ip = Yii::$app->getRequest()->getUserIP();
            $identity->last_login = time();

            // Prepare Cookie auth key
            $identity->setAuthKey();
            $identity->save();
        }

        StoreAdminsHash::updateFreshness($identity->id);

        return parent::beforeLogin($identity, $cookieBased, $duration); // TODO: Change the autogenerated stub
    }

    /** @inheritdoc */
    protected function afterLogout($identity)
    {
        /** @var StoreAdminAuth $identity */
        $identity->deleteAuthKey();

        parent::afterLogout($identity); // TODO: Change the autogenerated stub
    }

    /** @inheritdoc */
    protected function renewAuthStatus()
    {
        $this->loginByCookie();
    }
}