<?php
namespace console\controllers\gateway;

use console\components\MainController;
use Yii;

/**
 * Class CustomController
 * @package console\controllers\gateway
 */
class CustomController extends MainController
{
    public function init()
    {
        $this->frontendPath = Yii::getAlias('@gateway/config');

        Yii::$app->i18n->translations = [
            'yii' => [
                'class' => 'yii\i18n\PhpMessageSource',
                'basePath' => "@yii/messages",
                'sourceLanguage' => 'en',
            ],
            'app*' => [
                'class' => 'yii\i18n\PhpMessageSource',
                'basePath' => '@gateway/messages',
                'sourceLanguage' => 'en',
                'fileMap' => [
                    'app' => 'app.php',
                ],
            ],
        ];

        parent::init(); // TODO: Change the autogenerated stub
    }
}