<?php
namespace console\controllers\superadmin;

use Yii;
use console\components\MainMigrateController;

/**
 * Class CustomMigrateController
 * @package console\controllers\superadmin
 */
class CustomMigrateController extends MainMigrateController
{
    public function init()
    {
        $this->frontendPath = Yii::getAlias('@my/config');

        parent::init(); // TODO: Change the autogenerated stub
    }
}