<?php
namespace console\controllers\store;

use Yii;
use console\components\MainMigrateController;

/**
 * Class CustomMigrateController
 * @package console\controllers\store
 */
class CustomMigrateController extends MainMigrateController
{
    public function init()
    {
        $this->frontendPath = Yii::getAlias('@store/config');

        parent::init(); // TODO: Change the autogenerated stub
    }
}