<?php
namespace console\controllers\store;

use console\components\MainController;
use Yii;

/**
 * Class CustomController
 * @package console\controllers\store
 */
class CustomController extends MainController
{
    public function init()
    {
        $this->frontendPath = Yii::getAlias('@store/config');

        Yii::$app->i18n->translations = [
            'yii' => [
                'class' => 'yii\i18n\PhpMessageSource',
                'basePath' => "@yii/messages",
                'sourceLanguage' => 'en',
            ],
            'admin*' => [
                'class' => 'yii\i18n\PhpMessageSource',
                'basePath' => '@store/messages',
                'fileMap' => [
                    'admin' => 'admin.php',
                ],
            ],
            'app*' => [
                'class' => 'store\components\i18n\CustomMessageSource',
                'basePath' => '@store/messages',
            ],
        ];

        parent::init(); // TODO: Change the autogenerated stub
    }
}