<?php

namespace frontend\modules\admin\controllers;

use common\models\stores\StoreAdminAuth;
use common\models\stores\Stores;
use frontend\modules\admin\components\Url;
use Yii;
use frontend\controllers\CommonController;
use yii\web\User;

/**
 * Class AdminController
 * @package frontend\modules\admin\controllers
 */
class AdminController extends CommonController
{
    /** @inheritdoc */
    public function beforeAction($action)
    {
        /** @var User $user */
        $user = Yii::$app->user;

        /** @var Stores $store */
        $store = Yii::$app->store->getInstance();

        // Frozen/terminated store routine
        if ($store->isInactive()) {

            if (!$user->isGuest) {

                /** @var StoreAdminAuth $identity */
                $identity = $user->getIdentity(false);

                if (!$identity->isSuper()) {
                    $user->logout(true);
                }

            } elseif (!(Yii::$app->controller->id == 'site' && Yii::$app->controller->action->id == 'frozen')) {

                return $this->redirect(Url::toRoute('/frozen'));
            }
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}
