<?php

namespace frontend\modules\admin\controllers;

use Yii;
use common\components\MainController;
use yii\filters\AccessControl;

/**
 * Custom controller for the `admin` module
 */
class CustomController extends MainController
{
    public $activeTab;

    public $layout = '@admin/views/layouts/main.php';

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ]
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {
        $this->addModule('adminLayout');

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * Render content
     * @param string $view
     * @param array $params
     * @return string
     */
    public function render($view, $params = [])
    {
        $messages = Yii::$app->session->getFlash('messages');

        if (!empty($messages)) {
            $this->addModule('adminNotifyLayout', [
                'messages' => $messages
            ]);
        }

        return parent::render($view, $params); // TODO: Change the autogenerated stub
    }
}
