<?php

namespace common\components\email;

use Yii;
use yii\base\Exception;
use yii\base\Model;
use yii\helpers\ArrayHelper;

class Mailgun extends Model
{
    private $_mailgun_key;
    private $_mailgun_domain;

    private $_from_email;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->_mailgun_key = ArrayHelper::getValue(Yii::$app->params, 'mailgun.key', null);
        $this->_mailgun_domain = ArrayHelper::getValue(Yii::$app->params, 'mailgun.domain', null);

        $this->_from_email = ArrayHelper::getValue(Yii::$app->params, 'support_email', null);

        if (!$this->_mailgun_key && !$this->_mailgun_key) {
            throw new Exception('Mailgun is not yet configured! Check your app config params!');
        }

        if (!$this->_from_email) {
            throw new Exception('Support email not yet configured! Check your app config params!');
        }
    }

    /**
     * Send contact form email
     * @param $toEmail
     * @param $subject
     * @param $text
     * @return bool|mixed
     */
    public static function send($toEmail, $subject, $text)
    {
        $mail = new static();

        return static::_send($toEmail, $mail->_from_email, '', $subject, $text, $mail->_mailgun_domain, $mail->_mailgun_key);
    }

    /**
     * Send custom email throw Mailgun service
     * @param $toEmail
     * @param $fromEmail
     * @param $fromName
     * @param $subject
     * @param $text
     * @param $domain
     * @param $apiKey
     * @return mixed
     * @throws Exception
     */
    private static function _send($toEmail, $fromEmail, $fromName, $subject, $text, $domain, $apiKey)
    {
        //    curl -s --user 'api:YOUR_API_KEY' \
        //    https://api.mailgun.net/v3/YOUR_DOMAIN_NAME/messages \
        //    -F from='Excited User <mailgun@YOUR_DOMAIN_NAME>' \
        //    -F to=YOU@YOUR_DOMAIN_NAME \
        //    -F to=bar@example.com \
        //    -F subject='Hello' \
        //    -F text='Testing some Mailgun awesomeness!'

        // Get cURL resource
        $ch = curl_init();
        // Set some options - we are passing in a useragent too here
        curl_setopt_array($ch, [

            CURLOPT_USERPWD => 'api:' . $apiKey,
            CURLOPT_URL => "https://api.mailgun.net/v3/" . $domain . "/messages",

            CURLOPT_RETURNTRANSFER => 1,
            CURLOPT_POST => 1,
            CURLOPT_POSTFIELDS => [
                'from' => "$fromEmail",
                'to' => $toEmail,
                'subject' => $subject,
                'text' => $text,
            ]
        ]);

        $response = curl_exec($ch);

        if (curl_errno($ch)) {
            $firstError = curl_error($ch);
            curl_close($ch);
            throw new Exception("Curl initialisation error: $firstError");
        }

        curl_close($ch);

        $jsonResponse = json_decode($response, true);

        return $jsonResponse;
    }

}