<?php
/**
 * Package link types list
 * Uses for Package model, UI select elements, etc.
 */

return [
    "1" => "Instagram Profile",
    "2" => "Instagram Post",
    "3" => "Facebook Page",
    "4" => "Facebook Profile",
    "5" => "Facebook Post",
    "6" => "Facebook Group",
    "7" => "Facebook Event",
    "8" => "Twitter Profile",
    "9" => "Twitter Post",
    "10" => "Youtube Channel",
    "11" => "Youtube Video",
    "12" => "VINE Picture",
    "13" => "VINE Profile",
    "14" => "Pinterest Profile",
    "15" => "Pinterest Board",
    "16" => "Pinterest Post",
    "17" => "Soundcloud Track",
    "18" => "Soundcloud Profile",
    "19" => "Mixcloud Track",
    "20" => "Mixcloud Profile",
    "21" => "Periscope Profile",
    "22" => "Periscope Video",
    "25" => "Linkedin Profile",
    "26" => "Linkedin Group",
    "27" => "Linkedin Post",
    "28" => "Radiojavan Video",
    "29" => "Radiojavan Track",
    "30" => "Radiojavan Podcast",
    "31" => "Radiojavan Playlist",
    "32" => "Shazam Profile",
    "33" => "Shazam Track",
    "34" => "Reverbnation Track",
    "35" => "Reverbnation Video",
    "36" => "Reverbnation Profile",
    "37" => "Tumblr Profile",
    "38" => "Tumblr Post",
    "39" => "Vimeo Channel",
    "40" => "Vimeo Video",
    "41" => "Fyuse Profile",
    "42" => "Fyuse Picture",
    "43" => "Google+ Profile",
    "44" => "Google+ Post",
    "45" => "Twitch Channel",
];
