<?php

namespace admin\controllers;

use gateway\controllers\CommonController;
use Yii;
use yii\filters\AccessControl;
use yii\web\User;

/**
 * Custom controller for the `admin` module
 */
class CustomController extends CommonController
{
    public $activeTab;

    public $layout = '@admin/views/layouts/main.php';

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => false,
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
                'denyCallback' => function($rule, $action) {
                    Yii::$app->user->loginRequired();
                }
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function beforeAction($action)
    {
        /** @var User $user */
        $user = Yii::$app->user;

        // Frozen/terminated gateway routine
        if ($this->gateway->isInactive() && !$user->isGuest) {
            $user->logout();
        }

        $this->addModule('adminLayout');

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * Render content
     * @param string $view
     * @param array $params
     * @return string
     */
    public function render($view, $params = [])
    {
        $messages = Yii::$app->session->getFlash('messages');

        if (!empty($messages)) {
            $this->addModule('adminNotifyLayout', [
                'messages' => $messages
            ]);
        }

        return parent::render($view, $params); // TODO: Change the autogenerated stub
    }
}
