<?php
namespace admin\controllers;

use admin\components\Url;
use admin\models\forms\LoginForm;
use Yii;
use yii\filters\AccessControl;
use yii\web\User;

/**
 * Site controller for the `admin` module
 */
class SiteController extends CustomController
{
    /**
     * Layout for login pages
     * @var string
     */
    public $layout = '@admin/views/layouts/login.php';

    /**
     * Current first allowed redirect path
     * @var string
     */
    private $_loggedInRedirectUrl;

    /**
     * Instance of current user
     * @var User
     */
    private $_user;

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'admin\components\CustomErrorAction',
                'layout' => '@admin/views/layouts/main.php',
                'view' => '@admin/views/error/404',
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['index'],
                'rules' => [
                    [
                        'actions' => ['index'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['index'],
                        'allow' => false,
                        'roles' => ['@'],
                    ]
                ],

                /**
                 * Redirect logged in user to
                 * allowed controller from $_redirectOrderList
                 */
                'denyCallback' => function($rule, $action){

                    $this->redirect(Url::toRoute($this->_loggedInRedirectUrl));

                }
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function beforeAction($action)
    {
        $this->_user = Yii::$app->user;

        if (!$this->_user->isGuest) {
            $this->_makeRedirectUrl();
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {
        $this->view->title = Yii::t('admin', 'login.sign_in_page_title');

        $form = new LoginForm();

        if ($form->load(Yii::$app->getRequest()->post()) && $form->login()) {
            if ($this->gateway->isInactive()) {
                return $this->redirect(Url::toRoute('/frozen'));
            }

            $this->redirect(Url::toRoute($this->_loggedInRedirectUrl));
        }

        return $this->render('signin', [
            'form' => $form,
        ]);
    }

    /**
     * Render gateway frozen page for guest and non-superadmins
     * @return string
     */
    public function actionFrozen()
    {

        if (!$this->gateway->isInactive()) {
            return $this->redirect(Url::toRoute('/'));
        }

        return $this->renderPartial('frozen');
    }

    /**
     * Logout action.
     * @return string
     */
    public function actionLogout()
    {
        $user = Yii::$app->user;

        $user->logout();
        $user->loginRequired();
    }

    /**
     * Make redirect url for logged in user
     * If exist return Url, and it is allowed, use it.
     * Else use first allowed controller from _redirectList list
     * @return string
     */
    private function _makeRedirectUrl()
    {
        // Try to redirect by `return url`
        $returnUrl = $this->_user->getReturnUrl();
        if ($returnUrl) {

            $path = parse_url($returnUrl, PHP_URL_PATH);
            $parsedPath = explode('/', trim($path, '/'));

            if ($path && isset($parsedPath[1])) {
                // Check if $returnController allowed
                $this->_loggedInRedirectUrl = ltrim($returnUrl, '/admin');

                return $this->_loggedInRedirectUrl;
            }
        }

        $this->_loggedInRedirectUrl = '/account';

        return $this->_loggedInRedirectUrl;
    }
}
