<?php
namespace console\controllers\sommerce;

use console\components\MainController;
use Yii;

/**
 * Class CustomController
 * @package console\controllers\sommerce
 */
class CustomController extends MainController
{
    public function init()
    {
        $this->frontendPath = Yii::getAlias('@sommerce/config');

        parent::init(); // TODO: Change the autogenerated stub
    }
}