<?php
namespace console\controllers\sommerce;

use Yii;
use console\components\MainMigrateController;

/**
 * Class CustomMigrateController
 * @package console\controllers\sommerce
 */
class CustomMigrateController extends MainMigrateController
{
    public function init()
    {
        $this->frontendPath = Yii::getAlias('@sommerce/config');

        parent::init(); // TODO: Change the autogenerated stub
    }
}