<?php
namespace gateway\controllers;

use common\components\MainController;
use common\models\gateways\Sites;
use Yii;

/**
 * Custom controller for the Frontend and Admin module
 */
class CommonController extends MainController
{
    /**
     * @var $gateway Sites
     */
    public $gateway = null;

    /**
     * @inheritdoc
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $gateway = Yii::$app->gateway->getInstance();

        if (!$gateway || !($gateway instanceof Sites)) {
            exit;
        }

        $this->gateway = $gateway;
    }
}
