<?php
namespace console\controllers\my;

use Yii;
use yii\console\Controller;

/**
 * Class CustomController
 * @package console\controllers\my
 */
class CustomController extends Controller
{
    public function init()
    {
        $commonPath = Yii::getAlias('@common/config');
        $consolePath = Yii::getAlias('@console/config');
        $frontendPath = Yii::getAlias('@my/config');

        $params = array_merge(
            require_once($commonPath . '/params.php'),
            file_exists($commonPath . '/params-local.php') ? require_once($commonPath . '/params-local.php') : [],
            require_once($consolePath. '/params.php'),
            file_exists($consolePath . '/params-local.php') ? require_once($consolePath . '/params-local.php') : [],
            require_once($frontendPath. '/params.php'),
            file_exists($frontendPath . '/params-local.php') ? require_once($frontendPath . '/params-local.php') : []
        );

        Yii::$app->params = $params;

        parent::init(); // TODO: Change the autogenerated stub
    }
}