<?php

use yii\db\Migration;

/**
 * Class m180604_144044_db_store_product_overfollow_feature_added
 */
class m180604_144044_db_store_product_overfollow_feature_added extends Migration
{
    /**
     * Store template database
     * @var
     */
    private $databases;

    /**
     * {@inheritdoc}
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $databases = (new \yii\db\Query())->select([
            'db_name',
        ])->from(DB_STORES . '.stores')->column();

        $databases[] = Yii::$app->params['storeDefaultDatabase'];

        foreach ($databases as $key => $db) {
            $dbExist = Yii::$app->db
                ->createCommand("SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = '$db'")
                ->queryScalar();

            if (!$dbExist) {
                unset($databases[$key]);
            }
        }

        $this->databases = $databases;
    }

    /**
     * {@inheritdoc}
     */
    public function up()
    {
        foreach ($this->databases as $db) {
            $this->execute("
              ALTER TABLE  `{$db}`.`suborders` ADD `overflow_quantity` INT(11)  NULL  DEFAULT '0'  AFTER `quantity`;
            ");
            $this->execute("
              ALTER TABLE  `{$db}`.`packages` ADD `overflow` SMALLINT(3)  NULL  DEFAULT '0'  COMMENT '%, -100..100'  AFTER `quantity`;
            ");
        }
    }

    /**
     * {@inheritdoc}
     */
    public function down()
    {
        foreach ($this->databases as $db) {
            $this->execute("
              ALTER TABLE  `{$db}`.`suborders ` DROP `overflow_quantity `;
            ");
            $this->execute("
              ALTER TABLE `{$db}`.`packages` DROP `overflow`;
            ");
        }
    }
}
