<?php

use yii\db\Migration;

/**
 * Class m180406_111513_db_store_table_products__color_field_added
 */
class m180406_111513_db_store_table_products__color_field_added extends Migration
{
    /**
     * @var
     */
    protected $dbName;

    public function init()
    {
        $this->dbName = Yii::$app->params['storeDefaultDatabase'];
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {

    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        echo "m180406_111513_db_store_table_products__color_field_added cannot be reverted.\n";

        return false;
    }

    /**
     * {@inheritdoc}
     */
    public function up()
    {
        $this->execute("
            USE `$this->dbName`;
            ALTER TABLE `$this->dbName`.`products` ADD `color` VARCHAR(255)  NULL  DEFAULT NULL  AFTER `visibility`;
        ");
    }

    /**
     * {@inheritdoc}
     */
    public function down()
    {
        $this->execute("
            USE `$this->dbName`;
            ALTER TABLE `$this->dbName`.`products` DROP `color`;
        ");
    }
}
