<?php
/*
    symbol_aligment 1 - left, 2 - right
    mode standart, extended
*/
return array(
    'USD' => array(
        'id' => 1,
        'name' => 'United States Dollars',
        'symbol' => '$',
        'symbol_aligment' => '1',
        'gateway' => array(
            'paypal' => array(
                'method_name' => 'PayPal',
                'pgid' => 1,
                'url' => array(
                    'paypalexpress',
                    'paypalstandart',
                ),
                'mode' => 'standart',
                'name' => 'PayPal',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                    'username' => '',
                    'password' => '',
                    'signature' => '',
                ),
                'type' => 0,
                'position' => 1,
            ),
            'skrill' => array(
                'method_name' => 'Skrill',
                'pgid' => 6,
                'url' => 'skrill',
                'mode' => 'standart',
                'name' => 'Skrill',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                ),
                'type' => 0,
                'position' => 2,
            ),
            'payza' => array(
                'method_name' => 'Payza',
                'pgid' => 4,
                'url' => 'payza',
                'mode' => 'standart',
                'name' => 'Payza',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                ),
                'type' => 0,
                'position' => 3,
            ),
            'webmoney' => array(
                'method_name' => 'WebMoney',
                'pgid' => 3,
                'url' => 'webmoney',
                'mode' => 'standart',
                'name' => 'WebMoney',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'purse' => '',
                    'secret_key' => '',
                ),
                'type' => 0,
                'position' => 4,
            ),
            'perfectmoney' => array(
                'method_name' => 'Perfect Money',
                'pgid' => 2,
                'url' => 'perfectmoney',
                'mode' => 'standart',
                'name' => 'Perfect Money',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'account' => '',
                    'passphrase' => '',
                ),
                'type' => 0,
                'position' => 5,
            ),
            'zarinpal' => array(
                'method_name' => 'ZarinPal',
                'pgid' => 7,
                'url' => 'zarinpal',
                'mode' => 'standart',
                'name' => 'ZarinPal',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'MerchantID' => '',
                    'course' => '',
                ),
                'type' => 0,
                'allow' => array(
                    '133' => true,
                    '156' => true,
                    '301' => true,
                ),
                'position' => 6,
            ),
            'payeer' => array(
                'method_name' => 'Payeer',
                'pgid' => 19,
                'url' => 'payeer',
                'mode' => 'standart',
                'name' => 'Payeer',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'm_shop' => '',
                    'm_key' => '',
                ),
                'type' => 0,
                'position' => 7,
            ),
            'bitcoin' => array(
                'method_name' => 'Bitcoin',
                'pgid' => 14,
                'url' => 'bitcoin',
                'mode' => 'standart',
                'name' => 'Bitcoin',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 8,
            ),
            'coinpayments' => array(
                'method_name' => 'CoinPayments',
                'pgid' => 21,
                'url' => 'coinpayments',
                'mode' => 'standart',
                'name' => 'CoinPayments',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchant_id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 9,
            ),
            'payumoney' => array(
                'method_name' => 'PayUmoney',
                'pgid' => 16,
                'url' => 'payumoney',
                'mode' => 'standart',
                'name' => 'PayUmoney',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchantid' => '',
                    'merchantkey' => '',
                    'salt' => '',
                ),
                'type' => 0,
                'allow' => array(
                    '470' => true,
                    '133' => true,
                ),
                'position' => 10,
            ),
            'tap' => array(
                'method_name' => 'Tap',
                'pgid' => 24,
                'url' => 'tapcompany',
                'mode' => 'standart',
                'name' => 'Tap',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchant_id' => '',
                    'username' => '',
                    'password' => '',
                    'apikey' => '',
                ),
                'type' => 0,
                'allow' => array(
                    '133' => true,
                    '94' => true,
                ),
                'position' => 11,
            ),
            'paytm' => array(
                'method_name' => 'Paytm',
                'pgid' => 25,
                'url' => 'paytm',
                'mode' => 'standart',
                'name' => 'Paytm',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchant_key' => '',
                    'merchant_mid' => '',
                    'merchant_website' => '',
                    'course' => '',
                ),
                'type' => 0,
                'position' => 12,
            ),
        ),
    ),
    'RUB' => array(
        'id' => 2,
        'name' => 'Russian Rubles',
        'symbol' => ' руб.',
        'symbol_aligment' => '2',
        'gateway' => array(
            'webmoney' => array(
                'method_name' => 'WebMoney',
                'pgid' => 3,
                'url' => 'webmoney',
                'mode' => 'standart',
                'name' => 'WebMoney',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'purse' => '',
                    'secret_key' => '',
                ),
                'type' => 0,
                'position' => 1,
            ),
            'yandexmoney' => array(
                'method_name' => 'Yandex.Money',
                'pgid' => 10,
                'url' => 'yandex',
                'mode' => 'standart',
                'name' => 'Yandex.Money',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'wallet_number' => '',
                    'secret_word' => '',
                ),
                'type' => 0,
                'position' => 2,
            ),
            'liqpay' => array(
                'method_name' => 'LiqPay',
                'pgid' => 13,
                'url' => 'liqpay',
                'mode' => 'standart',
                'name' => 'LiqPay',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'public_key' => '',
                    'private_key' => '',
                ),
                'type' => 0,
                'position' => 3,
            ),
            'paypal' => array(
                'method_name' => 'PayPal',
                'pgid' => 1,
                'url' => array(
                    'paypalexpress',
                    'paypalstandart',
                ),
                'mode' => 'standart',
                'name' => 'PayPal',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                    'username' => '',
                    'password' => '',
                    'signature' => '',
                ),
                'type' => 0,
                'position' => 4,
            ),
            'yandexkassa' => array(
                'method_name' => 'Yandex.Kassa',
                'pgid' => 15,
                'url' => 'yandexkassa',
                'mode' => 'standart',
                'name' => 'Yandex.Kassa',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'scId' => '',
                    'shopId' => '',
                    'ShopPassword' => '',
                ),
                'type' => 0,
                'position' => 5,
            ),
            'interkassa' => array(
                'method_name' => 'Interkassa',
                'pgid' => 12,
                'url' => 'interkassa',
                'mode' => 'standart',
                'name' => 'Interkassa',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'id' => '',
                    'secret_key' => '',
                ),
                'type' => 0,
                'position' => 6,
            ),
            'freekassa' => array(
                'method_name' => 'Free-Kassa',
                'pgid' => 18,
                'url' => 'freekassa',
                'mode' => 'standart',
                'name' => 'Free-Kassa',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchant_id' => '',
                    'secret_word' => '',
                    'secret_word2' => '',
                ),
                'type' => 0,
                'position' => 7,
            ),
            'payeer' => array(
                'method_name' => 'Payeer',
                'pgid' => 19,
                'url' => 'payeer',
                'mode' => 'standart',
                'name' => 'Payeer',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'm_shop' => '',
                    'm_key' => '',
                ),
                'type' => 0,
                'position' => 8,
            ),
            'oplatainfo' => array(
                'method_name' => 'oplatainfo',
                'pgid' => 23,
                'url' => 'oplatainfo',
                'mode' => 'standart',
                'name' => 'OplataInfo',
                'minimal' => '3.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchant_id' => '',
                    'password' => '',
                    'product_id' => '',
                ),
                'type' => 0,
                'position' => 9,
            ),
            'bitcoin' => array(
                'method_name' => 'Bitcoin',
                'pgid' => 14,
                'url' => 'bitcoin',
                'mode' => 'standart',
                'name' => 'Bitcoin',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 10,
            ),
            'coinpayments' => array(
                'method_name' => 'CoinPayments',
                'pgid' => 21,
                'url' => 'coinpayments',
                'mode' => 'standart',
                'name' => 'CoinPayments',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchant_id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 11,
            ),
        ),
    ),
    'THB' => array(
        'id' => 3,
        'name' => 'Thai Baht',
        'symbol' => ' ฿',
        'symbol_aligment' => '2',
        'gateway' => array(
            'paypal' => array(
                'method_name' => 'PayPal',
                'pgid' => 1,
                'url' => array(
                    'paypalexpress',
                    'paypalstandart',
                ),
                'mode' => 'standart',
                'name' => 'PayPal',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                    'username' => '',
                    'password' => '',
                    'signature' => '',
                ),
                'type' => 0,
                'position' => 1,
            ),
            'coinpayments' => array(
                'method_name' => 'CoinPayments',
                'pgid' => 21,
                'url' => 'coinpayments',
                'mode' => 'standart',
                'name' => 'CoinPayments',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchant_id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 2,
            ),

        ),
    ),
    'TRY' => array(
        'id' => 4,
        'name' => 'Turkish Lira',
        'symbol' => '₺',
        // 'symbol' => ' TL',
        'symbol_aligment' => '2',
        'gateway' => array(
            'paypal' => array(
                'method_name' => 'PayPal',
                'pgid' => 1,
                'url' => array(
                    'paypalexpress',
                    'paypalstandart',
                ),
                'mode' => 'standart',
                'name' => 'PayPal',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                    'username' => '',
                    'password' => '',
                    'signature' => '',
                ),
                'type' => 0,
                'position' => 1,
            ),
            'skrill' => array(
                'method_name' => 'Skrill',
                'pgid' => 6,
                'url' => 'skrill',
                'mode' => 'standart',
                'name' => 'Skrill',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                ),
                'type' => 0,
                'position' => 2,
            ),
            'payza' => array(
                'method_name' => 'Payza',
                'pgid' => 4,
                'url' => 'payza',
                'mode' => 'standart',
                'name' => 'Payza',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                ),
                'type' => 0,
                'position' => 3,
            ),
            'paywant' => array(
                'method_name' => 'Paywant',
                'pgid' => 17,
                'url' => 'paywant',
                'mode' => 'standart',
                'name' => 'Paywant',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'apiKey' => '',
                    'apiSecret' => '',
                    'fee' => '',
                ),
                'type' => 0,
                'position' => 4,
            ),
            'bitcoin' => array(
                'method_name' => 'Bitcoin',
                'pgid' => 14,
                'url' => 'bitcoin',
                'mode' => 'standart',
                'name' => 'Bitcoin',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 5,
            ),
        ),
    ),
    'EUR' => array(
        'id' => 5,
        'name' => 'Euro',
        'symbol' => '€',
        'symbol_aligment' => '1',
        'gateway' => array(
            'paypal' => array(
                'method_name' => 'PayPal',
                'pgid' => 1,
                'url' => array(
                    'paypalexpress',
                    'paypalstandart',
                ),
                'mode' => 'standart',
                'name' => 'PayPal',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                    'username' => '',
                    'password' => '',
                    'signature' => '',
                ),
                'type' => 0,
                'position' => 1,
            ),
            'skrill' => array(
                'method_name' => 'Skrill',
                'pgid' => 6,
                'url' => 'skrill',
                'mode' => 'standart',
                'name' => 'Skrill',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                ),
                'type' => 0,
                'position' => 2,
            ),
            'payza' => array(
                'method_name' => 'Payza',
                'pgid' => 4,
                'url' => 'payza',
                'mode' => 'standart',
                'name' => 'Payza',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                ),
                'type' => 0,
                'position' => 3,
            ),
            'webmoney' => array(
                'method_name' => 'WebMoney',
                'pgid' => 3,
                'url' => 'webmoney',
                'mode' => 'standart',
                'name' => 'WebMoney',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'purse' => '',
                    'secret_key' => '',
                ),
                'type' => 0,
                'position' => 4,
            ),
            'perfectmoney' => array(
                'method_name' => 'Perfect Money',
                'pgid' => 2,
                'url' => 'perfectmoney',
                'mode' => 'standart',
                'name' => 'Perfect Money',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'account' => '',
                    'passphrase' => '',
                ),
                'type' => 0,
                'position' => 5,
            ),
            'bitcoin' => array(
                'method_name' => 'Bitcoin',
                'pgid' => 14,
                'url' => 'bitcoin',
                'mode' => 'standart',
                'name' => 'Bitcoin',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 7,
            ),
            'coinpayments' => array(
                'method_name' => 'CoinPayments',
                'pgid' => 21,
                'url' => 'coinpayments',
                'mode' => 'standart',
                'name' => 'CoinPayments',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchant_id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 8,
            ),
        ),
    ),
    'IDR' => array(
        'id' => 6,
        'name' => 'Indonesian Rupiah',
        'symbol' => 'Rp ',
        'symbol_aligment' => '1',
        'gateway' => array(
            'paypal' => array(
                'method_name' => 'PayPal',
                'pgid' => 1,
                'url' => array(
                    'paypalexpress',
                    'paypalstandart',
                ),
                'mode' => 'standart',
                'name' => 'PayPal',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                    'username' => '',
                    'password' => '',
                    'signature' => '',
                ),
                'type' => 0,
                'position' => 1,
            ),
            'coinpayments' => array(
                'method_name' => 'CoinPayments',
                'pgid' => 21,
                'url' => 'coinpayments',
                'mode' => 'standart',
                'name' => 'CoinPayments',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchant_id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 2,
            ),
        ),
    ),
    'BRL' => array(
        'id' => 7,
        'name' => 'Brazilian Real',
        'symbol' => 'R$',
        'symbol_aligment' => '1',
        'gateway' => array(
            'paypal' => array(
                'method_name' => 'PayPal',
                'pgid' => 1,
                'url' => array(
                    'paypalexpress',
                    'paypalstandart',
                ),
                'mode' => 'standart',
                'name' => 'PayPal',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                    'username' => '',
                    'password' => '',
                    'signature' => '',
                ),
                'type' => 0,
                'position' => 1,
            ),
            'coinpayments' => array(
                'method_name' => 'CoinPayments',
                'pgid' => 21,
                'url' => 'coinpayments',
                'mode' => 'standart',
                'name' => 'CoinPayments',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchant_id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 2,
            ),
            'mercadopago' => array(
                'method_name' => 'MercadoPago',
                'pgid' => 22,
                'url' => 'mercadopago',
                'mode' => 'standart',
                'name' => 'MercadoPago',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'client_id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 3,
            ),
        ),
    ),
    'CNY' => array(
        'id' => 8,
        'name' => 'Chinese Yuan',
        'symbol' => '¥',
        'symbol_aligment' => '1',
        'gateway' => array(
            'paypal' => array(
                'method_name' => 'PayPal',
                'pgid' => 1,
                'url' => array(
                    'paypalexpress',
                    'paypalstandart',
                ),
                'mode' => 'standart',
                'name' => 'PayPal',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                    'username' => '',
                    'password' => '',
                    'signature' => '',
                ),
                'type' => 0,
                'position' => 1,
            ),
            'bitcoin' => array(
                'method_name' => 'Bitcoin',
                'pgid' => 14,
                'url' => 'bitcoin',
                'mode' => 'standart',
                'name' => 'Bitcoin',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 2,
            ),
            'coinpayments' => array(
                'method_name' => 'CoinPayments',
                'pgid' => 21,
                'url' => 'coinpayments',
                'mode' => 'standart',
                'name' => 'CoinPayments',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchant_id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 3,
            ),
        ),
    ),
    'KRW' => array(
        'id' => 9,
        'name' => 'South Korean Won',
        'symbol' => '₩ ',
        'symbol_aligment' => '1',
        'gateway' => array(
            'paypal' => array(
                'method_name' => 'PayPal',
                'pgid' => 1,
                'url' => array(
                    'paypalexpress',
                    'paypalstandart',
                ),
                'mode' => 'standart',
                'name' => 'PayPal',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                    'username' => '',
                    'password' => '',
                    'signature' => '',
                ),
                'type' => 0,
                'position' => 1,
            ),
            'bitcoin' => array(
                'method_name' => 'Bitcoin',
                'pgid' => 14,
                'url' => 'bitcoin',
                'mode' => 'standart',
                'name' => 'Bitcoin',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 2,
            ),
            'coinpayments' => array(
                'method_name' => 'CoinPayments',
                'pgid' => 21,
                'url' => 'coinpayments',
                'mode' => 'standart',
                'name' => 'CoinPayments',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchant_id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 3,
            ),
        ),
    ),
    'INR' => array(
        'id' => 10,
        'name' => 'Indian Rupee',
        'symbol' => '₹',
        'symbol_aligment' => '1',
        'gateway' => array(
            'paypal' => array(
                'method_name' => 'PayPal',
                'pgid' => 1,
                'url' => array(
                    'paypalexpress',
                    'paypalstandart',
                ),
                'mode' => 'standart',
                'name' => 'PayPal',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                    'username' => '',
                    'password' => '',
                    'signature' => '',
                ),
                'type' => 0,
                'position' => 1,
            ),
            'payumoney' => array(
                'method_name' => 'PayUmoney',
                'pgid' => 16,
                'url' => 'payumoney',
                'mode' => 'standart',
                'name' => 'PayUmoney',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchantid' => '',
                    'merchantkey' => '',
                    'salt' => '',
                ),
                'type' => 0,
                'position' => 2,
            ),
            'bitcoin' => array(
                'method_name' => 'Bitcoin',
                'pgid' => 14,
                'url' => 'bitcoin',
                'mode' => 'standart',
                'name' => 'Bitcoin',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 3,
            ),
            'coinpayments' => array(
                'method_name' => 'CoinPayments',
                'pgid' => 21,
                'url' => 'coinpayments',
                'mode' => 'standart',
                'name' => 'CoinPayments',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchant_id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 4,
            ),
        ),
    ),
    'IRR' => array(
        'id' => 11,
        'name' => 'Iranian Rial',
        'symbol' => ' ﷼',
        'symbol_aligment' => '2',
        'gateway' => array(
            'zarinpal' => array(
                'method_name' => 'ZarinPal',
                'pgid' => 7,
                'url' => 'zarinpal',
                'mode' => 'standart',
                'name' => 'ZarinPal',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'MerchantID' => '',
                    'course' => '',
                ),
                'type' => 0,
                'position' => 1,
            ),
            'paytm' => array(
                'method_name' => 'Paytm',
                'pgid' => 25,
                'url' => 'paytm',
                'mode' => 'standart',
                'name' => 'Paytm',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchant_key' => '',
                    'merchant_mid' => '',
                    'merchant_website' => '',
                    'course' => '',
                ),
                'type' => 0,
                'position' => 2,
            ),
        ),
    ),
    'SAR' => array(
        'id' => 12,
        'name' => 'Saudi Arabia Riyal',
        'symbol' => ' ر.س',
        'symbol_aligment' => '2',
        'gateway' => array(),
    ),
    'PLN' => array(
        'id' => 13,
        'name' => 'Polish złoty',
        'symbol' => ' zl',
        'symbol_aligment' => '2',
        'gateway' => array(
            'paypal' => array(
                'method_name' => 'PayPal',
                'pgid' => 1,
                'url' => array(
                    'paypalexpress',
                    'paypalstandart',
                ),
                'mode' => 'standart',
                'name' => 'PayPal',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                    'username' => '',
                    'password' => '',
                    'signature' => '',
                ),
                'type' => 0,
                'position' => 1,
            ),
            'bitcoin' => array(
                'method_name' => 'Bitcoin',
                'pgid' => 14,
                'url' => 'bitcoin',
                'mode' => 'standart',
                'name' => 'Bitcoin',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 2,
            ),
            'coinpayments' => array(
                'method_name' => 'CoinPayments',
                'pgid' => 21,
                'url' => 'coinpayments',
                'mode' => 'standart',
                'name' => 'CoinPayments',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchant_id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 3,
            ),
        ),
    ),
    'MYR' => array(
        'id' => 14,
        'name' => 'Malaysian Ringgit',
        'symbol' => 'RM',
        'symbol_aligment' => '1',
        'gateway' => array(
            'paypal' => array(
                'method_name' => 'PayPal',
                'pgid' => 1,
                'url' => 'paypalexpress',
                'mode' => 'standart',
                'name' => 'PayPal',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                    'username' => '',
                    'password' => '',
                    'signature' => '',
                ),
                'type' => 0,
                'position' => 1,
            ),
            'billplz' => array(
                'method_name' => 'Billplz',
                'pgid' => 20,
                'url' => 'billplz',
                'mode' => 'standart',
                'name' => 'Billplz',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'collectionId' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 3,
            ),
            'bitcoin' => array(
                'method_name' => 'Bitcoin',
                'pgid' => 14,
                'url' => 'bitcoin',
                'mode' => 'standart',
                'name' => 'Bitcoin',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 2,
            ),
            'coinpayments' => array(
                'method_name' => 'CoinPayments',
                'pgid' => 21,
                'url' => 'coinpayments',
                'mode' => 'standart',
                'name' => 'CoinPayments',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchant_id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 4,
            ),
        ),
    ),
    'GBP' => array(
        'id' => 15,
        'name' => 'Pound sterling',
        'symbol' => '£',
        'symbol_aligment' => '1',
        'gateway' => array(
            'paypal' => array(
                'method_name' => 'PayPal',
                'pgid' => 1,
                'url' => 'paypalexpress',
                'mode' => 'standart',
                'name' => 'PayPal',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                    'username' => '',
                    'password' => '',
                    'signature' => '',
                ),
                'type' => 0,
                'position' => 1,
            ),
            'skrill' => array(
                'method_name' => 'Skrill',
                'pgid' => 6,
                'url' => 'skrill',
                'mode' => 'standart',
                'name' => 'Skrill',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                ),
                'type' => 0,
                'position' => 2,
            ),
            'payza' => array(
                'method_name' => 'Payza',
                'pgid' => 4,
                'url' => 'payza',
                'mode' => 'standart',
                'name' => 'Payza',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                ),
                'type' => 0,
                'position' => 3,
            ),
            'bitcoin' => array(
                'method_name' => 'Bitcoin',
                'pgid' => 14,
                'url' => 'bitcoin',
                'mode' => 'standart',
                'name' => 'Bitcoin',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 2,
            ),
            'coinpayments' => array(
                'method_name' => 'CoinPayments',
                'pgid' => 21,
                'url' => 'coinpayments',
                'mode' => 'standart',
                'name' => 'CoinPayments',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchant_id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 4,
            ),
        ),
    ),
);