<?php

/*
    symbol_aligment 1 - left, 2 - right
    mode standart, extended
*/
return array(
    'USD' => array(
        'id' => 1,
        'name' => 'United States Dollars',
        'symbol' => '$',
        'symbol_aligment' => '1',
        'gateway' => array(
            'paypal' => array(
                'method_name' => 'PayPal',
                'pgid' => 1,
                'url' => 'paypalexpress',
                'mode' => 'standart',
                'name' => 'PayPal',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                    'username' => '',
                    'password' => '',
                    'signature' => '',
                ),
                'type' => 0,
                'position' => 1,
            ),
            'paypalstandard' => array(
                'method_name' => 'PayPal Standard',
                'pgid' => 53,
                'url' => 'paypalstandard',
                'mode' => 'standart',
                'name' => 'PayPal Standard',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                    'username' => '',
                    'password' => '',
                    'signature' => '',
                ),
                'type' => 0,
                'position' => 3,
            ),

            'skrill' => array(
                'method_name' => 'Skrill',
                'pgid' => 6,
                'url' => 'skrill',
                'mode' => 'standart',
                'name' => 'Skrill',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                ),
                'type' => 0,
                'position' => 2,
            ),
            'payza' => array(
                'method_name' => 'Payza',
                'pgid' => 4,
                'url' => 'payza',
                'mode' => 'standart',
                'name' => 'Payza',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                ),
                'type' => 0,
                'position' => 3,
            ),
            'webmoney' => array(
                'method_name' => 'WebMoney',
                'pgid' => 3,
                'url' => 'webmoney',
                'mode' => 'standart',
                'name' => 'WebMoney',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'purse' => '',
                    'secret_key' => '',
                ),
                'type' => 0,
                'position' => 4,
            ),
            'perfectmoney' => array(
                'method_name' => 'Perfect Money',
                'pgid' => 2,
                'url' => 'perfectmoney',
                'mode' => 'standart',
                'name' => 'Perfect Money',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'account' => '',
                    'passphrase' => '',
                ),
                'type' => 0,
                'position' => 5,
            ),
            'zarinpal' => array(
                'method_name' => 'ZarinPal',
                'pgid' => 7,
                'url' => 'zarinpal',
                'mode' => 'standart',
                'name' => 'ZarinPal',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'MerchantID' => '',
                    'course' => '',
                ),
                'allow' => array(
                    '133' => true,
                    '88' => true,
                    '69' => true,
                    '156' => true,
                    '301' => true,
                ),
                'type' => 0,
                'position' => 6,
            ),
            'stripe' => array(
                'method_name' => 'Stripe',
                'pgid' => 32,
                'url' => 'stripe',
                'mode' => 'standart',
                'name' => 'Stripe',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'public_key' => '',
                    'secret_key' => '',
                    'webhook_secret' => '',
                    'image' => '',
                ),
                'user_options' => [
                    'token' => [
                        'name' => 'token',
                        'type' => 'hidden',
                    ],
                    'email' => [
                        'name' => 'email',
                        'type' => 'hidden',
                    ],
                ],
                'type' => 0,
                'position' => 7,
            ),
            'payeer' => array(
                'method_name' => 'Payeer',
                'pgid' => 19,
                'url' => 'payeer',
                'mode' => 'standart',
                'name' => 'Payeer',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'm_shop' => '',
                    'm_key' => '',
                ),
                'type' => 0,
                'position' => 8,
            ),
            'bitcoin' => array(
                'method_name' => 'Bitcoin',
                'pgid' => 14,
                'url' => 'bitcoin',
                'mode' => 'standart',
                'name' => 'Bitcoin',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 9,
            ),
            'coinpayments' => array(
                'method_name' => 'CoinPayments',
                'pgid' => 21,
                'url' => 'coinpayments',
                'mode' => 'standart',
                'name' => 'CoinPayments',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchant_id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 10,
            ),
            'payumoney' => array(
                'method_name' => 'PayUmoney',
                'pgid' => 16,
                'url' => 'payumoney',
                'mode' => 'standart',
                'name' => 'PayUmoney',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchantid' => '',
                    'merchantkey' => '',
                    'salt' => '',
                    'course' => '',
                ),
                'allow' => array(
                    '1286' => true,
                    '168' => true,
                    '1287' => true,
                    '29' => true,
                    '422' => true,
                    '1556' => true,
                    '439' => true,
                    '1782' => true,
                    '133' => true,
                    '1743' => true,
                    '1543' => true,
                    '1779' => true,
                    '1371' => true,
                    '1565' => true,
                    '1353' => true,
                    '157' => true,
                    '88' => true,
                    '1742' => true,
                    '1368' => true,
                    '1032' => true,
                    '505' => true,
                    '539' => true,
                    '1468' => true,
                    '767' => true,
                    '238' => true,
                    '1779' => true,
                    '972' => true,
                    '1187' => true,
                ),
                'type' => 0,
                'position' => 11,
            ),
            'instamojo' => array(
                'method_name' => 'Instamojo',
                'pgid' => 25,
                'url' => 'instamojo',
                'mode' => 'standart',
                'name' => 'Instamojo',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'api_key' => '',
                    'token' => '',
                    'salt' => '',
                    'course' => '',
                ),
                'allow' => array(
                    '133' => true,
                    '1286' => true,
                    '1475' => true,
                    '1287' => true,
                    '1032' => true,
                    '539' => true,
                    '999' => true,
                    '439' => true,
                    '157' => true,
                    '422' => true,
                ),
                'type' => 0,
                'position' => 13,
            ),
            'paywithpaytm' => array(
                'method_name' => 'Paytm Business',
                'pgid' => 33,
                'url' => 'paywithpaytm',
                'mode' => 'standart',
                'name' => 'Paytm',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchant_key' => '',
                    'merchant_mid' => '',
                    'course' => '',
                    'description' => '',
                    'test_mode' => 0,
                ),
                'user_options' => [
                    'description' => [
                        'label' => 'addfunds.instruction',
                        'name' => 'description',
                        'type' => 'container',
                    ],
                    'transaction_id' => [
                        'label' => 'addfunds.order_id',
                        'name' => 'transaction_id',
                        'value' => '',
                        'type' => 'input',
                        'rules' => [
                            ['transaction_id', 'required', 'message' => 'addfunds.error.transaction_id'],
                            ['transaction_id', 'string', 'message' => 'addfunds.error.transaction_id'],
                            ['transaction_id', 'method', 'message' => 'addfunds.error.transaction_id']
                        ]
                    ],
                    'submit' => [
                        'label' => 'addfunds.button.check',
                        'type' => 'button',
                    ],
                    'amount' => [
                        'label' => 'addfunds.paytm.amount',
                        'type' => 'label',
                    ],
                ],
                'allow' => array(
                    '1032' => true,
                    '1691' => true,
                    '999' => true,
                    '323' => true,
                    '1085' => true,
                    '1468' => true,
                    '1542' => true,
                    '1802' => true,
                    '1782' => true,
                    '133' => true,
                    '1412' => true,
                    '1905' => true,
                    '1353' => true,
                    '972' => true,
                    '1565' => true,
                    '216' => true,
                    '1742' => true,
                    '238' => true,
                    '1544' => true,
                    '1878' => true,
                    '178' => true,
                    '1543' => true,
                    '1243' => true,
                    '1476' => true,
                    '1187' => true,
                    '1547' => true,
                    '157' => true,
                    '1556' => true,
                    '1743' => true,
                    '933' => true,
                    '1541' => true,
                    '510' => true,
                    '1779' => true,
                    '1775' => true,
                    '1474' => true,
                    '1438' => true,
                    '819' => true,
                    '1475' => true,
                    '505' => true,
                    '439' => true,
                    '539' => true,
                    '422' => true,
                    '1287' => true,
                    '1286' => true,
                    '1198' => true,
                    '935' => true,
                    '692' => true,
                    '1196' => true,
                ),
                'type' => 0,
                'position' => 15,
            ),
            'paytmimap' => array(
                'method_name' => 'Paytm Personal',
                'pgid' => 37,
                'url' => 'paytm',
                'mode' => 'standart',
                'name' => 'Paytm',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'folder' => 'inbox',
                    'email' => '',
                    'password' => '',
                    'course' => '',
                    'instruction' => '',
                ),
                'user_options' => [
                    'description' => [
                        'label' => 'addfunds.instruction',
                        'name' => 'description',
                        'type' => 'container',
                    ],
                    'transaction_id' => [
                        'label' => 'addfunds.transaction_id',
                        'name' => 'transaction_id',
                        'value' => '',
                        'type' => 'input',
                        'rules' => [
                            ['transaction_id', 'required', 'message' => 'addfunds.error.transaction_id'],
                            ['transaction_id', 'string', 'message' => 'addfunds.error.transaction_id'],
                            ['transaction_id', 'method', 'message' => 'addfunds.error.transaction_id']
                        ]
                    ],
                    'submit' => [
                        'label' => 'addfunds.button.check',
                        'type' => 'button',
                    ],
                    'amount' => [
                        'label' => 'addfunds.paytm.amount',
                        'type' => 'label',
                    ],
                ],
                'allow' => array(
                    '133' => true,
                    '233' => true,
                    '1691' => true,
                    '1802' => true,
                    '448' => true,
                    '1779' => true,
                    '1543' => true,
                    '1286' => true,
                    '1287' => true,
                    '1353' => true,
                    '1565' => true,
                    '1368' => true,
                    '1371' => true,
                    '1742' => true,
                    '1526' => true,
                    '1544' => true,
                    '1556' => true,
                    '1743' => true,
                    '157' => true,
                    '1782' => true,
                    '510' => true,
                    '819' => true,
                    '1542' => true,
                    '999' => true,
                    '1476' => true,
                    '1438' => true,
                    '1475' => true,
                    '1032' => true,
                    '1187' => true,
                    '1196' => true,
                ),
                'type' => 0,
                'position' => 16,
            ),
            'hesabe' => array(
                'method_name' => 'Hesabe',
                'pgid' => 31,
                'url' => 'hesabe',
                'mode' => 'standart',
                'name' => 'Hesabe',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchant_code' => '',
                    'course' => '',
                ),
                'allow' => array(
                    '133' => true,
                    '94' => true,
                ),
                'type' => 0,
                'position' => 16,
            ),
            'mercadopago' => array(
                'method_name' => 'MercadoPago',
                'pgid' => 22,
                'url' => 'mercadopago',
                'mode' => 'standart',
                'name' => 'MercadoPago',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'client_id' => '',
                    'secret' => '',
                    'course' => '',
                ),
                'allow' => array(
                    '133' => true,
                    '940' => true,
                ),
                'type' => 0,
                'position' => 17,
            ),
            'authorize' => array(
                'method_name' => 'Authorize',
                'pgid' => 38,
                'url' => 'authorize',
                'mode' => 'standart',
                'name' => 'Authorize',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchant_client_key' => '',
                    'merchant_login_id' => '',
                    'merchant_transaction_id' => '',
                ),
                'user_options' => [
                    'data_descriptor' => [
                        'name' => 'data_descriptor',
                        'type' => 'hidden',
                    ],
                    'data_value' => [
                        'name' => 'data_value',
                        'type' => 'hidden',
                    ],
                ],
                'type' => 0,
                'position' => 19,
            ),
            'commercecoinbase' => array(
                'method_name' => 'Commerce Coinbase',
                'pgid' => 39,
                'url' => 'commercecoinbase',
                'mode' => 'standart',
                'name' => 'Commerce Coinbase',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'api_key' => '',
                    'webhook_key' => '',
                ),
                'type' => 0,
                'position' => 20,
            ),
            'tap' => array(
                'method_name' => 'Tap',
                'pgid' => 24,
                'url' => 'tapcompany',
                'mode' => 'standart',
                'name' => 'Tap',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchant_id' => '',
                    'username' => '',
                    'password' => '',
                    'apikey' => '',
                ),
                'allow' => array(
                    '133' => true,
                    '120' => true,
                    '1286' => true,
                    '106' => true,
                ),
                'type' => 0,
                'position' => 21,
            ),
            'mastercard' => array(
                'method_name' => 'Mastercard',
                'pgid' => 44,
                'url' => 'mastercard',
                'mode' => 'standart',
                'name' => 'Mastercard',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchant_id' => '',
                    'password' => '',
                    'webhook_secret' => '',
                ),
                'allow' => array(
                    '133' => true,
                    '907' => true,
                    '1' => true,
                ),
                'type' => 0,
                'position' => 22,
            ),
            'paypalInvoice' => array(
                'method_name' => 'PayPal Invoice',
                'pgid' => 46,
                'url' => 'paypalinvoice',
                'mode' => 'standart',
                'name' => 'PayPal Invoice',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 1,
                'fee' => 0,
                'options' => array(
                    'client_id' => '',
                    'secret' => '',
                    'email' => '',
                    'webhook_id' => '',
                    'descriptions' => []
                ),
                'allow' => [
                    '133' => true,
                    '4' => true,
                    '1880' => true,
                    '47' => true,
                    '924' => true,
                    '352' => true,
                    '1286' => true,
                    '697' => true,
                    '1287' => true,
                    '539' => true,
                    '1204' => true,
                    '581' => true,
                    '1955' => true,
                    '149' => true,
                    '129' => true,
                    '1008' => true,
                    '243' => true,
                    '24' => true,
                    '178' => true,
                    '157' => true,
                    '1779' => true,
                    '458' => true,
                    '1743' => true,
                    '1775' => true,
                    '1556' => true,
                    '566' => true,
                    '1413' => true,
                ],
                'user_options' => [
                    'paypal_email' => [
                        'label' => 'addfunds.paypal_email',
                        'name' => 'paypal_email',
                        'type' => 'input',
                        'rules' => [
                            ['paypal_email', 'required', 'message' => 'addfunds.error.email'],
                            ['paypal_email', 'email', 'message' => 'addfunds.error.email']
                        ]
                    ],


                ],
                'type' => 0,
                'position' => 23,
            ),
            'nganLuong' => array(
                'method_name' => 'NganLuong',
                'pgid' => 51,
                'url' => 'nganluong',
                'mode' => 'standart',
                'name' => 'NganLuong',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 1,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                    'merchant_id' => '',
                    'merchant_pass' => ''
                ),
                'allow' => [
                    '133' => true,
                    '1862' => true,
                    '1768' => true,
                ],
                'type' => 0,
                'position' => 24,
            ),
        ),
    ),
    'RUB' => array(
        'id' => 2,
        'name' => 'Russian Rubles',
        'symbol' => ' руб.',
        'symbol_aligment' => '2',
        'gateway' => array(
            'webmoney' => array(
                'method_name' => 'WebMoney',
                'pgid' => 3,
                'url' => 'webmoney',
                'mode' => 'standart',
                'name' => 'WebMoney',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'purse' => '',
                    'secret_key' => '',
                ),
                'type' => 0,
                'position' => 1,
            ),
            'yandexmoney' => array(
                'method_name' => 'Yandex.Money',
                'pgid' => 10,
                'url' => 'yandex',
                'mode' => 'standart',
                'name' => 'Yandex.Money',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'wallet_number' => '',
                    'secret_word' => '',
                ),
                'type' => 0,
                'position' => 2,
            ),
            'yandexcards' => array(
                'method_name' => 'Yandex.Cards',
                'pgid' => 36,
                'url' => 'yandex',
                'mode' => 'standart',
                'name' => 'Yandex.Cards',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'wallet_number' => '',
                    'secret_word' => '',
                ),
                'type' => 0,
                'position' => 3,
            ),
            'liqpay' => array(
                'method_name' => 'LiqPay',
                'pgid' => 13,
                'url' => 'liqpay',
                'mode' => 'standart',
                'name' => 'LiqPay',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'public_key' => '',
                    'private_key' => '',
                ),
                'type' => 0,
                'position' => 4,
            ),
            'paypal' => array(
                'method_name' => 'PayPal',
                'pgid' => 1,
                'url' => array(
                    'paypalexpress',
                    'paypalstandart',
                ),
                'mode' => 'standart',
                'name' => 'PayPal',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                    'username' => '',
                    'password' => '',
                    'signature' => '',
                ),
                'type' => 0,
                'position' => 5,
            ),
            'yandexkassa' => array(
                'method_name' => 'Yandex.Kassa',
                'pgid' => 15,
                'url' => 'yandexkassa',
                'mode' => 'standart',
                'name' => 'Yandex.Kassa',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'scId' => '',
                    'shopId' => '',
                    'ShopPassword' => '',
                ),
                'type' => 0,
                'position' => 6,
            ),
            'interkassa' => array(
                'method_name' => 'Interkassa',
                'pgid' => 12,
                'url' => 'interkassa',
                'mode' => 'standart',
                'name' => 'Interkassa',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'id' => '',
                    'secret_key' => '',
                ),
                'type' => 0,
                'position' => 7,
            ),
            'freekassa' => array(
                'method_name' => 'Free-Kassa',
                'pgid' => 18,
                'url' => 'freekassa',
                'mode' => 'standart',
                'name' => 'Free-Kassa',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchant_id' => '',
                    'secret_word' => '',
                    'secret_word2' => '',
                ),
                'type' => 0,
                'position' => 8,
            ),
            'payeer' => array(
                'method_name' => 'Payeer',
                'pgid' => 19,
                'url' => 'payeer',
                'mode' => 'standart',
                'name' => 'Payeer',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'm_shop' => '',
                    'm_key' => '',
                ),
                'type' => 0,
                'position' => 9,
            ),
            'oplatainfo' => array(
                'method_name' => 'oplatainfo',
                'pgid' => 23,
                'url' => 'oplatainfo',
                'mode' => 'standart',
                'name' => 'OplataInfo',
                'minimal' => '3.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchant_id' => '',
                    'password' => '',
                    'product_id' => '',
                ),
                'type' => 0,
                'position' => 10,
            ),
            'unitpay' => array(
                'method_name' => 'Unitpay',
                'pgid' => 28,
                'url' => 'unitpay',
                'mode' => 'standart',
                'name' => 'UnitPay',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'key' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 11,
            ),
            'qiwi' => array(
                'method_name' => 'Qiwi',
                'pgid' => 42,
                'url' => 'qiwi',
                'mode' => 'standart',
                'name' => 'Qiwi',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'token' => '',
                ),
                'user_options' => [
                    'instruction' => [
                        'label' => 'addfunds.instruction',
                        'name' => 'description',
                        'type' => 'container',
                    ],
                    'transaction_id' => [
                        'label' => 'addfunds.receipt',
                        'name' => 'transaction_id',
                        'value' => '',
                        'type' => 'input',
                        'rules' => [
                            ['transaction_id', 'required', 'message' => 'addfunds.error.transaction_id'],
                            ['transaction_id', 'string', 'message' => 'addfunds.error.transaction_id'],
                            ['transaction_id', 'method', 'message' => 'addfunds.error.transaction_id']
                        ]
                    ],
                    'submit' => [
                        'label' => 'addfunds.button.check',
                        'type' => 'button',
                    ],
                ],
                'type' => 0,
                'position' => 12,
            ),
            'bitcoin' => array(
                'method_name' => 'Bitcoin',
                'pgid' => 14,
                'url' => 'bitcoin',
                'mode' => 'standart',
                'name' => 'Bitcoin',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 13,
            ),
            'coinpayments' => array(
                'method_name' => 'CoinPayments',
                'pgid' => 21,
                'url' => 'coinpayments',
                'mode' => 'standart',
                'name' => 'CoinPayments',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchant_id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 14,
            ),
        ),
    ),
    'THB' => array(
        'id' => 3,
        'name' => 'Thai Baht',
        'symbol' => ' ฿',
        'symbol_aligment' => '2',
        'gateway' => array(
            'paypal' => array(
                'method_name' => 'PayPal',
                'pgid' => 1,
                'url' => array(
                    'paypalexpress',
                    'paypalstandart',
                ),
                'mode' => 'standart',
                'name' => 'PayPal',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                    'username' => '',
                    'password' => '',
                    'signature' => '',
                ),
                'type' => 0,
                'position' => 1,
            ),
            'coinpayments' => array(
                'method_name' => 'CoinPayments',
                'pgid' => 21,
                'url' => 'coinpayments',
                'mode' => 'standart',
                'name' => 'CoinPayments',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchant_id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 2,
            ),
            'kasikornbank' => array(
                'method_name' => 'Kasikornbank',
                'pgid' => 45,
                'url' => 'kasikornbank',
                'mode' => 'standart',
                'name' => 'Kasikornbank',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'login' => '',
                    'password' => '',
                    'account_number' => '',
                    'instruction' => '',
                ),
                'user_options' => [
                    'description' => [
                        'label' => 'addfunds.instruction',
                        'name' => 'description',
                        'type' => 'container',
                    ],
                ],
                'allow' => [
                    '133' => true,
                    '1515' => true,
                ],
                'type' => 0,
                'position' => 3,
            ),
        ),
    ),
    'TRY' => array(
        'id' => 4,
        'name' => 'Turkish Lira',
        'symbol' => '₺',
        // 'symbol' => ' TL',
        'symbol_aligment' => '2',
        'gateway' => array(
            'paypal' => array(
                'method_name' => 'PayPal',
                'pgid' => 1,
                'url' => array(
                    'paypalexpress',
                    'paypalstandart',
                ),
                'mode' => 'standart',
                'name' => 'PayPal',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                    'username' => '',
                    'password' => '',
                    'signature' => '',
                ),
                'type' => 0,
                'position' => 1,
            ),
            'skrill' => array(
                'method_name' => 'Skrill',
                'pgid' => 6,
                'url' => 'skrill',
                'mode' => 'standart',
                'name' => 'Skrill',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                ),
                'type' => 0,
                'position' => 2,
            ),
            'payza' => array(
                'method_name' => 'Payza',
                'pgid' => 4,
                'url' => 'payza',
                'mode' => 'standart',
                'name' => 'Payza',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                ),
                'type' => 0,
                'position' => 3,
            ),
            'paywant' => array(
                'method_name' => 'Paywant',
                'pgid' => 17,
                'url' => 'paywant',
                'mode' => 'standart',
                'name' => 'Paywant',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'apiKey' => '',
                    'apiSecret' => '',
                    'fee' => '',
                ),
                'type' => 0,
                'position' => 4,
            ),
            'bitcoin' => array(
                'method_name' => 'Bitcoin',
                'pgid' => 14,
                'url' => 'bitcoin',
                'mode' => 'standart',
                'name' => 'Bitcoin',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 5,
            ),
            'paytr' => array(
                'method_name' => 'Paytr',
                'pgid' => 29,
                'url' => 'paytr',
                'mode' => 'standart',
                'name' => 'Paytr',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchant_id ' => '',
                    'merchant_key' => '',
                    'merchant_salt' => '',
                    'commission' => ''
                ),
                'user_options' => [
                    'phone' => [
                        'label' => 'addfunds.phone',
                        'type' => 'input',
                        'rules' => [
                            ['phone', 'required', 'message' => 'addfunds.error.phone'],
                            ['phone', 'string', 'message' => 'addfunds.error.phone']
                        ]
                    ]
                ],
                'type' => 0,
                'position' => 6,
            ),
            'paytrhavale' => array(
                'method_name' => 'Paytrhavale',
                'pgid' => 43,
                'url' => 'paytr',
                'mode' => 'standart',
                'name' => 'PayTR Havale/EFT',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchant_id ' => '',
                    'merchant_key' => '',
                    'merchant_salt' => '',
                    'commission' => ''
                ),
                'user_options' => [
                    'phone' => [
                        'label' => 'addfunds.phone',
                        'type' => 'input',
                        'rules' => [
                            ['phone', 'required', 'message' => 'addfunds.error.phone'],
                            ['phone', 'string', 'message' => 'addfunds.error.phone']
                        ]
                    ]
                ],
                'type' => 0,
                'position' => 7,
            ),
            'buypayer' => array(
                'method_name' => 'Buypayer',
                'pgid' => 40,
                'url' => 'buypayer',
                'mode' => 'standart',
                'name' => 'Buypayer',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => [
                    'merchant_id ' => '',
                    'merchant_code' => '',
                    'merchant_email' => '',
                    'fee' => '',
                ],
                'type' => 0,
                'position' => 8,
            ),
            'coinpayments' => array(
                'method_name' => 'CoinPayments',
                'pgid' => 21,
                'url' => 'coinpayments',
                'mode' => 'standart',
                'name' => 'CoinPayments',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchant_id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 9,
            ),
            'commercecoinbase' => array(
                'method_name' => 'Commerce Coinbase',
                'pgid' => 39,
                'url' => 'commercecoinbase',
                'mode' => 'standart',
                'name' => 'Commerce Coinbase',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'api_key' => '',
                    'webhook_key' => '',
                ),
                'type' => 0,
                'position' => 10,
            ),
            'payamar' => array(
                'method_name' => 'Payamar',
                'pgid' => 48,
                'url' => 'payamar',
                'mode' => 'standart',
                'name' => 'Payamar',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchant_id ' => '',
                    'merchant_key' => '',
                    'merchant_salt' => '',
                ),
                'user_options' => [
                    'phone' => [
                        'label' => 'addfunds.phone',
                        'type' => 'input',
                        'rules' => [
                            ['phone', 'required', 'message' => 'addfunds.error.phone'],
                            ['phone', 'string', 'message' => 'addfunds.error.phone']
                        ]
                    ],
                    'address' => [
                        'label' => 'addfunds.address',
                        'type' => 'input',
                        'rules' => [
                            ['address', 'required', 'message' => 'addfunds.error.address'],
                            ['address', 'string', 'message' => 'addfunds.error.address']
                        ]
                    ]
                ],
                'allow' => array(
                    '133' => true,
                    '1766' => true,
                    '1188' => true,
                    '813' => true,
                    '747' => true,
                    '626' => true,
                    '1238' => true,
                    '1055' => true,
                    '812' => true,
                ),
                'type' => 0,
                'position' => 9,
            ),
            'payguru' => array(
                'method_name' => 'Payguru',
                'pgid' => 50,
                'url' => 'payguru',
                'mode' => 'standart',
                'name' => 'Payguru',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'allow' => [
                    '133' => true,
                    '709' => true,
                ],
                'options' => array(
                    'merchant_id ' => '',
                    'service_id' => '',
                    'category' => '',
                    'secret_key' => ''
                ),
                'type' => 0,
                'position' => 10,
            ),
        ),
    ),
    'EUR' => array(
        'id' => 5,
        'name' => 'Euro',
        'symbol' => '€',
        'symbol_aligment' => '1',
        'gateway' => array(
            'paypal' => array(
                'method_name' => 'PayPal',
                'pgid' => 1,
                'url' => array(
                    'paypalexpress',
                    'paypalstandart',
                ),
                'mode' => 'standart',
                'name' => 'PayPal',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                    'username' => '',
                    'password' => '',
                    'signature' => '',
                ),
                'type' => 0,
                'position' => 1,
            ),
            'skrill' => array(
                'method_name' => 'Skrill',
                'pgid' => 6,
                'url' => 'skrill',
                'mode' => 'standart',
                'name' => 'Skrill',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                ),
                'type' => 0,
                'position' => 2,
            ),
            'payza' => array(
                'method_name' => 'Payza',
                'pgid' => 4,
                'url' => 'payza',
                'mode' => 'standart',
                'name' => 'Payza',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                ),
                'type' => 0,
                'position' => 3,
            ),
            'webmoney' => array(
                'method_name' => 'WebMoney',
                'pgid' => 3,
                'url' => 'webmoney',
                'mode' => 'standart',
                'name' => 'WebMoney',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'purse' => '',
                    'secret_key' => '',
                ),
                'type' => 0,
                'position' => 4,
            ),
            'perfectmoney' => array(
                'method_name' => 'Perfect Money',
                'pgid' => 2,
                'url' => 'perfectmoney',
                'mode' => 'standart',
                'name' => 'Perfect Money',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'account' => '',
                    'passphrase' => '',
                ),
                'type' => 0,
                'position' => 5,
            ),
            'bitcoin' => array(
                'method_name' => 'Bitcoin',
                'pgid' => 14,
                'url' => 'bitcoin',
                'mode' => 'standart',
                'name' => 'Bitcoin',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 7,
            ),
            'coinpayments' => array(
                'method_name' => 'CoinPayments',
                'pgid' => 21,
                'url' => 'coinpayments',
                'mode' => 'standart',
                'name' => 'CoinPayments',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchant_id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 8,
            ),
            'payeer' => array(
                'method_name' => 'Payeer',
                'pgid' => 19,
                'url' => 'payeer',
                'mode' => 'standart',
                'name' => 'Payeer',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'm_shop' => '',
                    'm_key' => '',
                ),
                'type' => 0,
                'position' => 9,
            ),
            'mollie' => array(
                'method_name' => 'Mollie',
                'pgid' => 52,
                'url' => 'mollie',
                'mode' => 'standart',
                'name' => 'Mollie',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 1,
                'fee' => 0,
                'options' => array(
                    'api_key' => ''
                ),
                'type' => 0,
                'position' => 10,
            ),
        ),
    ),
    'IDR' => array(
        'id' => 6,
        'name' => 'Indonesian Rupiah',
        'symbol' => 'Rp ',
        'symbol_aligment' => '1',
        'gateway' => array(
            'paypal' => array(
                'method_name' => 'PayPal',
                'pgid' => 1,
                'url' => array(
                    'paypalexpress',
                    'paypalstandart',
                ),
                'mode' => 'standart',
                'name' => 'PayPal',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                    'username' => '',
                    'password' => '',
                    'signature' => '',
                ),
                'type' => 0,
                'position' => 1,
            ),
            'doku' => array(
                'method_name' => 'Doku',
                'pgid' => 30,
                'url' => 'doku',
                'mode' => 'standart',
                'name' => 'Doku',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'mall_id' => '',
                    'shared_key' => '',
                ),
                'type' => 0,
                'position' => 2,
            ),
            'coinpayments' => array(
                'method_name' => 'CoinPayments',
                'pgid' => 21,
                'url' => 'coinpayments',
                'mode' => 'standart',
                'name' => 'CoinPayments',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchant_id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 3,
            ),
            'klikbca' => array(
                'method_name' => 'Bank BCA',
                'pgid' => 35,
                'url' => 'klikbca',
                'mode' => 'standart',
                'name' => 'Bank BCA',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'user_id' => '',
                    'bank_pin' => '',
                    'instruction' => '',
                ),
                'user_options' => [
                    'description' => [
                        'label' => 'addfunds.instruction',
                        'name' => 'description',
                        'type' => 'container',
                    ],
                ],
                'allow' => array(
                    '133' => true,
                    '653' => true,
                    '1808' => true,
                ),
                'type' => 0,
                'position' => 4,
            ),
            'midtrans' => array(
                'method_name' => 'Midtrans',
                'pgid' => 49,
                'url' => 'midtrans',
                'mode' => 'standart',
                'name' => 'Midtrans',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'server_key' => '',
                    'client_key' => ''
                ),
                'allow' => [
                    '133' => true,
                    '653' => true,
                ],
                'type' => 0,
                'position' => 5,
            ),
        ),
    ),
    'BRL' => array(
        'id' => 7,
        'name' => 'Brazilian Real',
        'symbol' => 'R$',
        'symbol_aligment' => '1',
        'gateway' => array(
            'paypal' => array(
                'method_name' => 'PayPal',
                'pgid' => 1,
                'url' => array(
                    'paypalexpress',
                    'paypalstandart',
                ),
                'mode' => 'standart',
                'name' => 'PayPal',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                    'username' => '',
                    'password' => '',
                    'signature' => '',
                ),
                'type' => 0,
                'position' => 1,
            ),
            'coinpayments' => array(
                'method_name' => 'CoinPayments',
                'pgid' => 21,
                'url' => 'coinpayments',
                'mode' => 'standart',
                'name' => 'CoinPayments',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchant_id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 2,
            ),
            'mercadopago' => array(
                'method_name' => 'MercadoPago',
                'pgid' => 22,
                'url' => 'mercadopago',
                'mode' => 'standart',
                'name' => 'MercadoPago',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'client_id' => '',
                    'secret' => '',
                    'course' => '',
                ),
                'type' => 0,
                'position' => 3,
            ),
            'pagseguro' => array(
                'method_name' => 'PagSeguro',
                'pgid' => 26,
                'url' => 'pagseguro',
                'mode' => 'standart',
                'name' => 'PagSeguro',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                    'token' => '',
                ),
                'type' => 0,
                'position' => 4,
            ),
        ),
    ),
    'CNY' => array(
        'id' => 8,
        'name' => 'Chinese Yuan',
        'symbol' => '¥',
        'symbol_aligment' => '1',
        'gateway' => array(
            'paypal' => array(
                'method_name' => 'PayPal',
                'pgid' => 1,
                'url' => array(
                    'paypalexpress',
                    'paypalstandart',
                ),
                'mode' => 'standart',
                'name' => 'PayPal',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                    'username' => '',
                    'password' => '',
                    'signature' => '',
                ),
                'type' => 0,
                'position' => 1,
            ),
            'bitcoin' => array(
                'method_name' => 'Bitcoin',
                'pgid' => 14,
                'url' => 'bitcoin',
                'mode' => 'standart',
                'name' => 'Bitcoin',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 2,
            ),
            'coinpayments' => array(
                'method_name' => 'CoinPayments',
                'pgid' => 21,
                'url' => 'coinpayments',
                'mode' => 'standart',
                'name' => 'CoinPayments',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchant_id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 3,
            ),
        ),
    ),
    'KRW' => array(
        'id' => 9,
        'name' => 'South Korean Won',
        'symbol' => '₩ ',
        'symbol_aligment' => '1',
        'gateway' => array(
            'paypal' => array(
                'method_name' => 'PayPal',
                'pgid' => 1,
                'url' => array(
                    'paypalexpress',
                    'paypalstandart',
                ),
                'mode' => 'standart',
                'name' => 'PayPal',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                    'username' => '',
                    'password' => '',
                    'signature' => '',
                ),
                'type' => 0,
                'position' => 1,
            ),
            'bitcoin' => array(
                'method_name' => 'Bitcoin',
                'pgid' => 14,
                'url' => 'bitcoin',
                'mode' => 'standart',
                'name' => 'Bitcoin',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 2,
            ),
            'coinpayments' => array(
                'method_name' => 'CoinPayments',
                'pgid' => 21,
                'url' => 'coinpayments',
                'mode' => 'standart',
                'name' => 'CoinPayments',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchant_id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 3,
            ),
        ),
    ),
    'INR' => array(
        'id' => 10,
        'name' => 'Indian Rupee',
        'symbol' => '₹',
        'symbol_aligment' => '1',
        'gateway' => array(
            'paypal' => array(
                'method_name' => 'PayPal',
                'pgid' => 1,
                'url' => array(
                    'paypalexpress',
                    'paypalstandart',
                ),
                'mode' => 'standart',
                'name' => 'PayPal',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                    'username' => '',
                    'password' => '',
                    'signature' => '',
                ),
                'type' => 0,
                'position' => 1,
            ),
            'payumoney' => array(
                'method_name' => 'PayUmoney',
                'pgid' => 16,
                'url' => 'payumoney',
                'mode' => 'standart',
                'name' => 'PayUmoney',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchantid' => '',
                    'merchantkey' => '',
                    'salt' => '',
                    'course' => '',
                ),
                'type' => 0,
                'position' => 2,
            ),
            'instamojo' => array(
                'method_name' => 'Instamojo',
                'pgid' => 25,
                'url' => 'instamojo',
                'mode' => 'standart',
                'name' => 'Instamojo',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'api_key' => '',
                    'token' => '',
                    'salt' => '',
                    'course' => '',
                ),
                'type' => 0,
                'position' => 4,
            ),
            'paywithpaytm' => array(
                'method_name' => 'Paytm Business',
                'pgid' => 33,
                'url' => 'paywithpaytm',
                'mode' => 'standart',
                'name' => 'Paytm',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchant_key' => '',
                    'merchant_mid' => '',
                    'course' => '',
                    'description' => '',
                    'test_mode' => 0,
                ),
                'user_options' => [
                    'description' => [
                        'label' => 'addfunds.instruction',
                        'name' => 'description',
                        'type' => 'container',
                    ],
                    'transaction_id' => [
                        'label' => 'addfunds.order_id',
                        'name' => 'transaction_id',
                        'value' => '',
                        'type' => 'input',
                        'rules' => [
                            ['transaction_id', 'required', 'message' => 'addfunds.error.transaction_id'],
                            ['transaction_id', 'string', 'message' => 'addfunds.error.transaction_id'],
                            ['transaction_id', 'method', 'message' => 'addfunds.error.transaction_id']
                        ]
                    ],
                    'submit' => [
                        'label' => 'addfunds.button.check',
                        'type' => 'button',
                    ],
                    'amount' => [
                        'label' => 'addfunds.paytm.amount',
                        'type' => 'label',
                    ],
                ],
                'type' => 0,
                'position' => 5,
            ),
            'bitcoin' => array(
                'method_name' => 'Bitcoin',
                'pgid' => 14,
                'url' => 'bitcoin',
                'mode' => 'standart',
                'name' => 'Bitcoin',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 6,
            ),
            'coinpayments' => array(
                'method_name' => 'CoinPayments',
                'pgid' => 21,
                'url' => 'coinpayments',
                'mode' => 'standart',
                'name' => 'CoinPayments',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchant_id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 7,
            ),
            'paytmimap' => array(
                'method_name' => 'Paytm Personal',
                'pgid' => 37,
                'url' => 'paytm',
                'mode' => 'standart',
                'name' => 'Paytm',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'folder' => 'inbox',
                    'email' => '',
                    'password' => '',
                    'course' => '',
                    'instruction' => '',
                ),
                'user_options' => [
                    'description' => [
                        'label' => 'addfunds.instruction',
                        'name' => 'description',
                        'type' => 'container',
                    ],
                    'transaction_id' => [
                        'label' => 'addfunds.transaction_id',
                        'name' => 'transaction_id',
                        'value' => '',
                        'type' => 'input',
                        'rules' => [
                            ['transaction_id', 'required', 'message' => 'addfunds.error.transaction_id'],
                            ['transaction_id', 'string', 'message' => 'addfunds.error.transaction_id'],
                            ['transaction_id', 'method', 'message' => 'addfunds.error.transaction_id']
                        ]
                    ],
                    'submit' => [
                        'label' => 'addfunds.button.check',
                        'type' => 'button',
                    ],
                    'amount' => [
                        'label' => 'addfunds.paytm.amount',
                        'type' => 'label',
                    ],
                ],
                'allow' => array(
                    '133' => true,
                    '1064' => true,
                    '1032' => true,
                ),
                'type' => 0,
                'position' => 8,
            ),
        ),
    ),
    'IRR' => array(
        'id' => 11,
        'name' => 'Iranian Rial',
        'symbol' => ' ﷼',
        'symbol_aligment' => '2',
        'gateway' => array(
            'zarinpal' => array(
                'method_name' => 'ZarinPal',
                'pgid' => 7,
                'url' => 'zarinpal',
                'mode' => 'standart',
                'name' => 'ZarinPal',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'MerchantID' => '',
                    'course' => '',
                ),
                'type' => 0,
                'position' => 1,
            ),
        ),
    ),
    'SAR' => array(
        'id' => 12,
        'name' => 'Saudi Arabia Riyal',
        'symbol' => ' ر.س',
        'symbol_aligment' => '2',
        'gateway' => array(
            'tap' => array(
                'method_name' => 'Tap',
                'pgid' => 24,
                'url' => 'tapcompany',
                'mode' => 'standart',
                'name' => 'Tap',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchant_id' => '',
                    'username' => '',
                    'password' => '',
                    'apikey' => '',
                ),
                'type' => 0,
                'position' => 1,
            ),
        ),
    ),
    'PLN' => array(
        'id' => 13,
        'name' => 'Polish złoty',
        'symbol' => ' zl',
        'symbol_aligment' => '2',
        'gateway' => array(
            'paypal' => array(
                'method_name' => 'PayPal',
                'pgid' => 1,
                'url' => array(
                    'paypalexpress',
                    'paypalstandart',
                ),
                'mode' => 'standart',
                'name' => 'PayPal',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                    'username' => '',
                    'password' => '',
                    'signature' => '',
                ),
                'type' => 0,
                'position' => 1,
            ),
            'przelewy24' => array(
                'method_name' => 'Przelewy24',
                'pgid' => 41,
                'url' => 'przelewy24',
                'mode' => 'standart',
                'name' => 'Przelewy24',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchant_id' => '',
                    'pos_id' => '',
                    'salt' => '',
                    'test_mode'=> 0
                ),
                'type' => 0,
                'position' => 2,
            ),
            'bitcoin' => array(
                'method_name' => 'Bitcoin',
                'pgid' => 14,
                'url' => 'bitcoin',
                'mode' => 'standart',
                'name' => 'Bitcoin',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 3,
            ),
            'coinpayments' => array(
                'method_name' => 'CoinPayments',
                'pgid' => 21,
                'url' => 'coinpayments',
                'mode' => 'standart',
                'name' => 'CoinPayments',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchant_id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 4,
            ),
        ),
    ),
    'MYR' => array(
        'id' => 14,
        'name' => 'Malaysian Ringgit',
        'symbol' => 'RM',
        'symbol_aligment' => '1',
        'gateway' => array(
            'paypal' => array(
                'method_name' => 'PayPal',
                'pgid' => 1,
                'url' => 'paypalexpress',
                'mode' => 'standart',
                'name' => 'PayPal',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                    'username' => '',
                    'password' => '',
                    'signature' => '',
                ),
                'type' => 0,
                'position' => 1,
            ),
            'billplz' => array(
                'method_name' => 'Billplz',
                'pgid' => 20,
                'url' => 'billplz',
                'mode' => 'standart',
                'name' => 'Billplz',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'collectionId' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 3,
            ),
            'bitcoin' => array(
                'method_name' => 'Bitcoin',
                'pgid' => 14,
                'url' => 'bitcoin',
                'mode' => 'standart',
                'name' => 'Bitcoin',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 2,
            ),
            'coinpayments' => array(
                'method_name' => 'CoinPayments',
                'pgid' => 21,
                'url' => 'coinpayments',
                'mode' => 'standart',
                'name' => 'CoinPayments',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchant_id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 4,
            ),
            'senangpay' => array(
                'method_name' => 'Senangpay',
                'pgid' => 47,
                'url' => 'senangpay',
                'mode' => 'standart',
                'name' => 'SenangPay',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchant_id' => '',
                    'secret_key' => '',
                ),
                'allow' => [
                    '133' => true,
                    '1405' => true,
                ],
                'type' => 0,
                'position' => 5,
            ),
            'stripe' => array(
                'method_name' => 'Stripe',
                'pgid' => 32,
                'url' => 'stripe',
                'mode' => 'standart',
                'name' => 'Stripe',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'public_key' => '',
                    'secret_key' => '',
                    'webhook_secret' => '',
                    'image' => '',
                ),
                'user_options' => [
                    'token' => [
                        'name' => 'token',
                        'type' => 'hidden',
                    ],
                    'email' => [
                        'name' => 'email',
                        'type' => 'hidden',
                    ],
                ],
                'type' => 0,
                'position' => 6,
            ),
        ),
    ),
    'GBP' => array(
        'id' => 15,
        'name' => 'Pound sterling',
        'symbol' => '£',
        'symbol_aligment' => '1',
        'gateway' => array(
            'paypal' => array(
                'method_name' => 'PayPal',
                'pgid' => 1,
                'url' => 'paypalexpress',
                'mode' => 'standart',
                'name' => 'PayPal',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                    'username' => '',
                    'password' => '',
                    'signature' => '',
                ),
                'type' => 0,
                'position' => 1,
            ),
            'skrill' => array(
                'method_name' => 'Skrill',
                'pgid' => 6,
                'url' => 'skrill',
                'mode' => 'standart',
                'name' => 'Skrill',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                ),
                'type' => 0,
                'position' => 2,
            ),
            'payza' => array(
                'method_name' => 'Payza',
                'pgid' => 4,
                'url' => 'payza',
                'mode' => 'standart',
                'name' => 'Payza',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                ),
                'type' => 0,
                'position' => 3,
            ),
            'bitcoin' => array(
                'method_name' => 'Bitcoin',
                'pgid' => 14,
                'url' => 'bitcoin',
                'mode' => 'standart',
                'name' => 'Bitcoin',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 2,
            ),
            'coinpayments' => array(
                'method_name' => 'CoinPayments',
                'pgid' => 21,
                'url' => 'coinpayments',
                'mode' => 'standart',
                'name' => 'CoinPayments',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchant_id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 4,
            ),
        ),
    ),
    'KWD' => array(
        'id' => 16,
        'name' => 'Kuwaiti dinar',
        'symbol' => ' د.ك',
        'symbol_aligment' => '2',
        'gateway' => array(),
    ),
    'SEK' => array(
        'id' => 17,
        'name' => 'Swedish krona',
        'symbol' => ' kr',
        'symbol_aligment' => '2',
        'gateway' => array(
            'paypal' => array(
                'method_name' => 'PayPal',
                'pgid' => 1,
                'url' => array(
                    'paypalexpress',
                    'paypalstandart',
                ),
                'mode' => 'standart',
                'name' => 'PayPal',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                    'username' => '',
                    'password' => '',
                    'signature' => '',
                ),
                'type' => 0,
                'position' => 1,
            ),
            'skrill' => array(
                'method_name' => 'Skrill',
                'pgid' => 6,
                'url' => 'skrill',
                'mode' => 'standart',
                'name' => 'Skrill',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                ),
                'type' => 0,
                'position' => 2,
            ),
            'payza' => array(
                'method_name' => 'Payza',
                'pgid' => 4,
                'url' => 'payza',
                'mode' => 'standart',
                'name' => 'Payza',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                ),
                'type' => 0,
                'position' => 3,
            ),
            'bitcoin' => array(
                'method_name' => 'Bitcoin',
                'pgid' => 14,
                'url' => 'bitcoin',
                'mode' => 'standart',
                'name' => 'Bitcoin',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 4,
            ),
            'coinpayments' => array(
                'method_name' => 'CoinPayments',
                'pgid' => 21,
                'url' => 'coinpayments',
                'mode' => 'standart',
                'name' => 'CoinPayments',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchant_id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 5,
            ),
        ),
    ),
    'ILS' => array(
        'id' => 18,
        'name' => 'Israeli shekel',
        'symbol' => '₪',
        'symbol_aligment' => '1',
        'gateway' => array(
            'paypal' => array(
                'method_name' => 'PayPal',
                'pgid' => 1,
                'url' => array(
                    'paypalexpress',
                    'paypalstandart',
                ),
                'mode' => 'standart',
                'name' => 'PayPal',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                    'username' => '',
                    'password' => '',
                    'signature' => '',
                ),
                'type' => 0,
                'position' => 1,
            ),
            'coinpayments' => array(
                'method_name' => 'CoinPayments',
                'pgid' => 21,
                'url' => 'coinpayments',
                'mode' => 'standart',
                'name' => 'CoinPayments',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchant_id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 2,
            ),
        ),
    ),
    'HKD' => array(
        'id' => 19,
        'name' => 'Hong Kong dollar',
        'symbol' => 'HK$',
        'symbol_aligment' => '1',
        'gateway' => array(
            'paypal' => array(
                'method_name' => 'PayPal',
                'pgid' => 1,
                'url' => array(
                    'paypalexpress',
                    'paypalstandart',
                ),
                'mode' => 'standart',
                'name' => 'PayPal',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                    'username' => '',
                    'password' => '',
                    'signature' => '',
                ),
                'type' => 0,
                'position' => 1,
            ),
            'coinpayments' => array(
                'method_name' => 'CoinPayments',
                'pgid' => 21,
                'url' => 'coinpayments',
                'mode' => 'standart',
                'name' => 'CoinPayments',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'merchant_id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 2,
            ),
        ),
    ),
    'NGN' => array(
        'id' => 20,
        'name' => 'Nigerian naira',
        'symbol' => '₦',
        'symbol_aligment' => '1',
        'gateway' => array(

        ),
    ),
    'KES' => array(
        'id' => 21,
        'name' => 'Kenyan shilling',
        'symbol' => 'Ksh',
        'symbol_aligment' => '1',
        'gateway' => array(

        ),
    ),
    'JPY' => array(
        'id' => 22,
        'name' => 'Japanese Yen',
        'symbol' => '¥',
        'symbol_aligment' => '1',
        'gateway' => array(
            'paypal' => array(
                'method_name' => 'PayPal',
                'pgid' => 1,
                'url' => array(
                    'paypalexpress',
                    'paypalstandart',
                ),
                'mode' => 'standart',
                'name' => 'PayPal',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                    'username' => '',
                    'password' => '',
                    'signature' => '',
                ),
                'type' => 0,
                'position' => 1,
            ),
            'bitcoin' => array(
                'method_name' => 'Bitcoin',
                'pgid' => 14,
                'url' => 'bitcoin',
                'mode' => 'standart',
                'name' => 'Bitcoin',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'id' => '',
                    'secret' => '',
                ),
                'type' => 0,
                'position' => 2,
            ),
        ),
    ),
    'ARS' => array(
        'id' => 23,
        'name' => 'Argentine peso',
        'symbol' => '$',
        'symbol_aligment' => '1',
        'gateway' => array(
            'mercadopago' => array(
                'method_name' => 'MercadoPago',
                'pgid' => 22,
                'url' => 'mercadopago',
                'mode' => 'standart',
                'name' => 'MercadoPago',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 0,
                'fee' => 0,
                'options' => array(
                    'client_id' => '',
                    'secret' => '',
                    'course' => '',
                ),
                'allow' => array(
                    '133' => true,
                    '940' => true,
                ),
                'type' => 0,
                'position' => 1,
            ),
        ),
    ),
    'VND' => array(
        'id' => 24,
        'name' => 'Vietnamese đồng',
        'symbol' => '₫',
        'symbol_aligment' => '2',
        'gateway' => [
            'nganLuong' => array(
                'method_name' => 'NganLuong',
                'pgid' => 51,
                'url' => 'nganluong',
                'mode' => 'standart',
                'name' => 'NganLuong',
                'minimal' => '1.00',
                'maximal' => 0,
                'new_users' => '1',
                'visibility' => 1,
                'fee' => 0,
                'options' => array(
                    'email' => '',
                    'merchant_id' => '',
                    'merchant_pass' => ''
                ),
                'allow' => [
                    '1862' => true,
                    '1768' => true,
                ],
                'type' => 0,
                'position' => 1,
            ),

        ],
    ),

    'IQD' => array(
        'id' => 26,
        'name' => 'Iraqi dinar',
        'symbol' => 'د.ع',
        'symbol_aligment' => '1',
        'gateway' => [

        ],
    ),
);