                var templates = {};
                

templates['checkout/checkbox'] = _.template("<div class=\"form-group fields\" id=\"order_<%= name %>\">\n    <label class=\"control-label\" for=\"field-<%= name %>\"><%= label %><\/label><br>\n    <input name=\"fields[<%= name %>]\" value=\"0\" type=\"hidden\"/>\n    <input name=\"fields[<%= name %>]\" value=\"1\" type=\"checkbox\" id=\"field-<%= name %>\"/>\n<\/div>");

templates['checkout/description'] = _.template("<div class=\"form-group fields\" id=\"order_<%= name %>\">\n    <label class=\"control-label\" for=\"field-<%= name %>\"><%= label %><\/label>\n    <div class=\"panel-body border-solid border-rounded text-center\"><%= value %><\/div>\n<\/div>");

templates['checkout/hidden'] = _.template("<input class=\"fields\" name=\"fields[<%= name %>]\" value=\"<%= value %>\" type=\"hidden\" id=\"field-<%= name %>\"/>");

templates['checkout/input'] = _.template("<div class=\"form-group fields\" id=\"order_<%= name %>\">\n    <label class=\"control-label\" for=\"field-<%= name %>\"><%= label %><\/label>\n    <input class=\"form-control\" name=\"fields[<%= name %>]\" value=\"<%= value %>\" type=\"text\" id=\"field-<%= name %>\"/>\n<\/div>");

templates['checkout/stripe_payment_request_btn'] = _.template("<span id=\"<%= id %>\" style=\"width: 150px; height: 18px; display: inline-block;\" class=\"hidden\"><\/span>");

templates['modal/confirm'] = _.template("<div class=\"modal fade confirm-modal\" id=\"confirmModal\" tabindex=\"-1\" data-backdrop=\"static\">\n    <div class=\"modal-dialog modal-md\" role=\"document\">\n        <div class=\"modal-content\">\n            <% if (typeof(confirm_message) !== \"undefined\" && confirm_message != \'\') { %>\n            <div class=\"modal-header\">\n                <h3 id=\"conrirm_label\"><%= title %><\/h3>\n                <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\"><span aria-hidden=\"true\">&times;<\/span><\/button>\n            <\/div>\n\n            <div class=\"modal-body\">\n                <p><%= confirm_message %><\/p>\n            <\/div>\n\n\n            <div class=\"modal-footer justify-content-start\">\n                <button class=\"btn btn-primary m-btn--air\" id=\"confirm_yes\"><%= confirm_button %><\/button>\n                <button class=\"btn btn-secondary m-btn--air\" data-dismiss=\"modal\" aria-hidden=\"true\"><%= cancel_button %><\/button>\n            <\/div>\n            <% } else { %>\n            <div class=\"modal-body\">\n                <div class=\"text-center\">\n                    <h3 id=\"conrirm_label\"><%= title %><\/h3>\n                <\/div>\n\n                <div class=\"text-center\">\n                    <button class=\"btn btn-primary m-btn--air\" id=\"confirm_yes\"><%= confirm_button %><\/button>\n                    <button class=\"btn btn-secondary m-btn--air\" data-dismiss=\"modal\" aria-hidden=\"true\"><%= cancel_button %><\/button>\n                <\/div>\n            <\/div>\n            <% } %>\n        <\/div>\n    <\/div>\n<\/div>");